// 演唱会数据
// 由 generate_all.py 自动生成，请勿手动修改

const livesData = [
  {
    name: "Ave Mujica 0th LIVE「Primo die in scaena」",
    hash_id: "55U3JgpFudO",
    date: "2023/6/4",
    venue: "中野サンプラザホール",
    tag: "One Man Live",
    poster: "../images/logo/0th logo透明底.webp",
    kv: "../images/0th kv假.webp",
    video_url: "https://www.bilibili.com/video/BV1QsnXzBEWb/",
    description: "「初次登台」",
    for_short: "0th",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": ""}, {"num": "M01", "title": "黒のバースデイ", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539"}, {"num": "M02", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Originally by angela「K」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931710"}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "ホントウノワタシ -再生-“真正的我”", "mc_file": "mc/0th_再生.md", "link": "", "mc_content": "<p><h1>[c7]ホントウノワタシ -再生-[/c7]</h1></p><p>生きることは緩やかに死んでいくのと同じ。けれど、ほら見て。<br>何度でも生まれ変わればいい。変えて、作り直して、また生まれればいいの。<br>今からが「本当の私」なのよ。<div class=\"manual-br\"></div>♪ 5音音階1の音<div class=\"manual-br\"></div>♪ ノートに筆記する音<br>♪ メッセージの通知音<br>♪ ペンを置く音<br>♪ スマホを起動してメッセージを返す音<div class=\"manual-br\"></div>莉伽：ありがとう<br>莉伽：溜息<div class=\"manual-br\"></div>莉伽：くだらない。<br>勉強も部活も新しい人間関係も。<br>趣味も恋人もなんもない。<br>誇りも努力も平坦で、<br>それとなく、擬態した、変化のない毎日。<br>一生、幕の上がることのない人生。<br>高校に上がってもそれは変わらなかった。<div class=\"manual-br\"></div>莉伽：くだらない。<br>それとなく見てる動画配信、<br>それとなく投稿してるSNS、<br>どこかで通知されたからそれとなく送ってくる誕生日のメッセージ。<br>全部明日になれば忘れてる。<br>時間を消費するためだけの、アイテム。<br>思考させないための、檻。<div class=\"manual-br\"></div>♪ 動画投稿サイトを見ている。曲が一瞬だけ流れる。飛ばして見ている。<br>♪ 黑のバースデイで止まる。後ろで少し流れる。<div class=\"manual-br\"></div>莉伽：ぶらっくばーすでー。<br>誰だろう。<br>再生数も少ない。<br>新しバンド？違うか。<br>概要欄にも大したことは書いてない。<br>あ、リンク。<br>パスワードかな…。<br>へー<div class=\"manual-br\"></div>♪ 文字を打つ音。13音。BLACKBIRTHDAY<div class=\"manual-br\"></div>♪ 5音音階1の音<div class=\"manual-br\"></div>莉伽：そこに行くのは、きっと私だ。</p><p>[translation]</p><p><h1>[c7]“真正的我” -再生-[/c7]</h1></p><p>生存如同缓慢地走向死亡。然而，你看。<br>只要一次次地重生即可。一次次改变，一次次重塑，然后再度重生即可。<br>从此刻起才是「真正的我」。<div class=\"manual-br\"></div>♪ 五声音阶的第1个音<div class=\"manual-br\"></div>♪ 在笔记本上写字的声音<br>♪ 消息通知音<br>♪ 放下笔的声音<br>♪ 开屏手机并回复消息的声音<div class=\"manual-br\"></div>莉伽：“谢…谢…你…”<br>莉伽：叹气<div class=\"manual-br\"></div>莉伽：无聊透顶。<br>学习也好，社团活动也好，新的人际关系也是。<br>没有爱好，没有恋人，一无所有。<br>自尊心和努力都平平凡凡，<br>若无其事地、伪装着的、一成不变的每一天。<br>一辈子都不会拉开帷幕的人生。<br>即便升上高中一切依然如故。<div class=\"manual-br\"></div>莉伽：无聊透顶。<br>无意识地看着视频流，<br>无意识地在社交媒体上投稿，<br>\"因为不知从哪里来的通知<br>而无意识地发送的生日祝福。\"<br>所有的一切到了明日都将被遗忘。<br>只是用来消磨时间的，道具。<br>用来阻止思考的，牢笼。<div class=\"manual-br\"></div>♪ 正在浏览视频投稿网站。歌曲只播放了一瞬间。跳跃着观看。<br>♪ 停在黑色生日。稍微播放了一小段。<div class=\"manual-br\"></div>莉伽：黑色生日。<br>是谁啊。<br>播放量也很少。<br>新的乐团？好像不是。<br>简介栏里面也没写什么东西。<br>啊，链接。<br>这是密码吗…<br>嗯……<div class=\"manual-br\"></div>♪ 打字的声音。13个音。BLACKBIRTHDAY<div class=\"manual-br\"></div>♪ 五声音阶的第1个音<div class=\"manual-br\"></div>莉伽：要去那里的，毫无疑问是我。</p>"}, {"num": "M03", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931075"}, {"num": "M04", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932937"}, {"num": "M05", "title": "Determination Symphony", "highlight_label": "COVER", "highlight_text": "Originally by Roselia「ONENESS」收录曲", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935835"}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "マヨイコンダモリ -探索-“迷失于深林”", "mc_file": "", "link": ""}, {"num": "M06", "title": "Choir 'S' Choir", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101"}, {"num": "M07", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932763"}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "コタエヲサガシテ -摩擦-“寻找答案”", "mc_file": "", "link": ""}, {"num": "M08", "title": "神さま、バカ", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950"}, {"num": "M09", "title": "PASSIONATE ANTHEM", "highlight_label": "COVER", "highlight_text": "Originally by Roselia「Safe and Sound」收录曲", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935862"}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "キオクトゲンソウ -過去-“记忆与幻想”", "mc_file": "", "link": ""}, {"num": "M10", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303"}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "カクセイヘノウタ -招待-“通往觉醒之歌”", "mc_file": "", "link": ""}, {"num": "M11", "title": "Ave Mujica", "highlight_label": "Unreleased Song", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758"}],
    backstage: [{"photo": "../images/0thlive返图1.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图2.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图3.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图4.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图5.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图6.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图7.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图8.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图9.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "yes", "group_id": "0th LIVE 官推"}]
  },
  {
    name: "Roselia「Farbe」DAY2",
    hash_id: "TggVuqCpHD7",
    date: "2023/9/17",
    venue: "有明アリーナ",
    tag: "BanG Dream!",
    poster: "../images/logo/farbe logo.webp",
    kv: "../images/farbe kv假.webp",
    video_url: "https://www.bilibili.com/video/BV1meqBY9EjL",
    description: "Opening Act",
    for_short: "Roselia Farbe",
    setlist: [{"num": "M01", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_2"}, {"num": "M02", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_2"}, {"num": "M03", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_2"}],
    backstage: []
  },
  {
    name: "Ave Mujica 1st LIVE 「Perdere Omnia」",
    hash_id: "bZbRdPnEto9",
    date: "2024/1/27",
    venue: "横須賀芸術劇場",
    tag: "One Man Live",
    poster: "../images/logo/1st logo.webp",
    kv: "../images/1st live kv.webp",
    video_url: "https://www.bilibili.com/video/BV1XwFGzzEfn",
    description: "「破坏一切」",
    for_short: "1st",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "Anime", "highlight_text": "「BanG Dream! It's MyGO!!!!!」EP13", "mc_file": "", "link": ""}, {"num": "M01", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_3"}, {"num": "M02", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931075_2"}, {"num": "M03", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Originally by angela「K」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931710_2"}, {"num": "", "title": "Interlude", "highlight_label": "theatrical segment", "highlight_text": "预录音轨演出", "mc_file": "", "link": ""}, {"num": "M04", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675"}, {"num": "M05", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932937_2"}, {"num": "M06", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_2"}, {"num": "", "title": "Interlude", "highlight_label": "theatrical segment", "highlight_text": "预录音轨演出", "mc_file": "", "link": ""}, {"num": "M07", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "Highlight", "highlight_text": "Doloris尖叫ver", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_3"}, {"num": "M08", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932763_2"}, {"num": "M09", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_3"}, {"num": "", "title": "Interlude", "highlight_label": "theatrical segment", "highlight_text": "预录音轨演出", "mc_file": "", "link": ""}, {"num": "M10", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_2"}, {"num": "M11", "title": "Angles", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931167"}],
    backstage: []
  },
  {
    name: "MEGA VEGAS 2024",
    hash_id: "5kd22JxNEBm",
    date: "2024/3/9",
    venue: "神戸ワールド記念ホール",
    tag: "Fes",
    poster: "../images/logo/megavegas2024.webp",
    kv: "../images/megavegas2024 kv.webp",
    video_url: "",
    description: "",
    for_short: "MEGA VEGAS 2024",
    setlist: [{"num": "M01", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M05", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M06", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M07", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "Ave Mujica 2nd LIVE「Quaerere Lumina」神奈川公演",
    hash_id: "pwKWf8XfWUh",
    date: "2024/6/8",
    venue: "神奈川県民ホール 大ホール",
    tag: "One Man Live",
    poster: "../images/logo/2ndlogo神奈川.webp",
    kv: "../images/2nd live kv.webp",
    video_url: "https://www.bilibili.com/video/BV1nBoYYLE2C",
    description: "「寻找着光」",
    for_short: "2nd神奈川",
    setlist: [{"num": "M01", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_2"}, {"num": "M02", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_4"}, {"num": "M03", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931167_2"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M04", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932937_3"}, {"num": "M05", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_4"}, {"num": "M06", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_4"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M07", "title": "Symbol I : 🜂", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569"}, {"num": "M08", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Originally by angela「K」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931710_3"}, {"num": "M09", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932763_3"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M10", "title": "Symbol II : 🜁", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063"}, {"num": "M11", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_3"}, {"num": "M12", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931075_3"}, {"num": "M13", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_3"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "", "title": "Outro", "highlight_label": "Instrumental", "highlight_text": "Symbol III : 🜄伴奏", "mc_file": "", "link": ""}],
    backstage: []
  },
  {
    name: "Ave Mujica 2nd LIVE「Quaerere Lumina」爱知公演",
    hash_id: "whlteE6TZyU",
    date: "2024/7/7",
    venue: "愛知県芸術劇場 大ホール",
    tag: "One Man Live",
    poster: "../images/logo/2ndlogo爱知.webp",
    kv: "../images/2nd live kv.webp",
    video_url: "",
    description: "「寻找着光」",
    for_short: "2nd爱知",
    setlist: [{"num": "M01", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M04", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "0"}, {"num": "M05", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M06", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M07", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M08", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Originally by angela「K」OP", "mc_file": "", "link": "0"}, {"num": "M09", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": "", "link": "0"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M10", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M11", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M12", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M13", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M14", "title": "Symbol III : 🜄", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "BILIBILI MACRO LINK 2024 DAY1",
    hash_id: "KFsoVe6eUZD",
    date: "2024/7/13",
    venue: "国家会展中心（上海）虹馆EH",
    tag: "Fes",
    poster: "../images/logo/bml2024d1.webp",
    kv: "../images/bml2024 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1P142187fx",
    description: "非全场",
    for_short: "BML2024 D1",
    setlist: [{"num": "M01", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_5"}, {"num": "M02", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "BILIBILI MACRO LINK 2024 DAY2",
    hash_id: "UV4LeIl0gsu",
    date: "2024/7/14",
    venue: "国家会展中心（上海）虹馆EH",
    tag: "Fes",
    poster: "../images/logo/bml2024d2.webp",
    kv: "../images/bml2024 kv.webp",
    video_url: "",
    description: "",
    for_short: "BML2024 D2",
    setlist: [{"num": "M01", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "Animelo Summer Live 2024 -Stargazer-",
    hash_id: "VH1QmNswE34",
    date: "2024/8/30",
    venue: "さいたまスーパーアリーナ",
    tag: "Fes",
    poster: "../images/logo/asl2024logo.webp",
    kv: "../images/asl2024 kv.webp",
    video_url: "https://www.acfun.cn/v/ac48796276",
    description: "",
    for_short: "ASL2024",
    setlist: [{"num": "M00", "title": "Greensleeves", "highlight_label": "Highlight", "highlight_text": "Doloris清唱绿袖子开场", "mc_file": "", "link": ""}, {"num": "M01", "title": "Ave Mujica", "highlight_label": "Highlight", "highlight_text": "演唱前进行舞台名唱名", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_6"}, {"num": "M02", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_5"}],
    backstage: [{"photo": "../images/asl2024_am01.webp", "credit": "@SPICE", "credit_text": "SPICE LIVE返图", "source_url": "https://spice.eplus.jp/articles/331632", "source_label": "", "group_id": ""}, {"photo": "../images/asl2024_am02.webp", "credit": "@NATALIE", "credit_text": "NATALIE LIVE返图", "source_url": "https://natalie.mu/comic/gallery/news/588794/2400212", "source_label": "", "group_id": ""}]
  },
  {
    name: "Ave Mujica 3rd LIVE「Veritas」",
    hash_id: "ouGBqqrLUX6",
    date: "2024/10/13",
    venue: "河口湖ステラシアター",
    tag: "One Man Live",
    poster: "../images/logo/3rd logo.webp",
    kv: "../images/3rd live kv.webp",
    video_url: "https://www.bilibili.com/video/BV1owo9Y8EDX",
    description: "「真实」",
    for_short: "3rd",
    setlist: [{"num": "M01", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_3"}, {"num": "M02", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_2"}, {"num": "M03", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_2"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白，现代舞", "mc_file": "", "link": ""}, {"num": "M04", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_5"}, {"num": "M05", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931075_4"}, {"num": "M06", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932937_4"}, {"num": "M07", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_4"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白，现代舞", "mc_file": "", "link": ""}, {"num": "M08", "title": "Symbol III : 🜄", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965"}, {"num": "M09", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_6"}, {"num": "M10", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932763_4"}, {"num": "M11", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_7"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白，现代舞", "mc_file": "", "link": ""}, {"num": "M12", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931167_3"}, {"num": "M13", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_4"}, {"num": "M14", "title": "Symbol IV : 🜃", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934854"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白，现代舞", "mc_file": "", "link": ""}, {"num": "M15", "title": "Ether", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933636"}],
    backstage: []
  },
  {
    name: "ANIMAX MUSIX 2024 FALL",
    hash_id: "EXt2Qqxs1hA",
    date: "2024/11/23",
    venue: "横浜アリーナ",
    tag: "Fes",
    poster: "../images/logo/animax2024logo.webp",
    kv: "../images/animax2024 kv.webp",
    video_url: "https://www.acfun.cn/v/ac48796259",
    description: "",
    for_short: "ANIMAX 2024",
    setlist: [{"num": "M01", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_8"}, {"num": "M02", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_3"}, {"num": "M03", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "with Sizuk Originally by ALI PROJECT「小女神花铃」OP", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932937_5"}],
    backstage: []
  },
  {
    name: "Roselia「Stille Nacht, Rosen Nacht」",
    hash_id: "CpeV3O2ZxLA",
    date: "2024/12/14",
    venue: "武蔵野の森総合スポーツプラザ",
    tag: "BanG Dream!",
    poster: "../images/logo/roseliasnrnlogo.webp",
    kv: "../images/roseliasnrn kv.webp",
    video_url: "https://www.acfun.cn/v/ac48786156",
    description: "Opening Act",
    for_short: "Roselia SNRN",
    setlist: [{"num": "M01", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_4"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_3"}, {"num": "M03", "title": "Symbol III : 🜄", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965_2"}, {"num": "M04", "title": "Symbol IV : 🜃", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934854_2"}, {"num": "M05", "title": "Ether", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933636_2"}],
    backstage: [{"photo": "../images/roseliasnrn_am01.webp", "credit": "@SPICE", "credit_text": "SPICE LIVE返图", "source_url": "https://spice.eplus.jp/articles/334303", "source_label": "", "group_id": "roseliasnrn全员"}, {"photo": "../images/roseliasnrn_am02.webp", "credit": "@SPICE", "credit_text": "SPICE LIVE返图", "source_url": "https://spice.eplus.jp/articles/334303", "source_label": "", "group_id": "roseliasnrn全员"}, {"photo": "../images/roseliasnrn_am03.webp", "credit": "@SPICE", "credit_text": "SPICE LIVE返图", "source_url": "https://spice.eplus.jp/articles/334303", "source_label": "", "group_id": "roseliasnrn全员"}]
  },
  {
    name: "Ave Mujica 4th LIVE「Adventus」",
    hash_id: "XhSboBDdeqk",
    date: "2024/12/15",
    venue: "武蔵野の森総合スポーツプラザ",
    tag: "One Man Live",
    poster: "../images/logo/4th logo.webp",
    kv: "../images/4th live kv.webp",
    video_url: "https://www.bilibili.com/video/BV1czEszBEWw",
    description: "「降临」",
    for_short: "4th",
    setlist: [{"num": "M01", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_5"}, {"num": "M02", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931075_5"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "现场表演念白", "mc_file": "", "link": ""}, {"num": "M03", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_5"}, {"num": "M04", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_6"}, {"num": "", "title": "Piano Solo", "highlight_label": "Solo", "highlight_text": "自作编曲", "mc_file": "", "link": ""}, {"num": "M05", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_7"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! It's MyGO!!!!!」EP13", "mc_file": "", "link": ""}, {"num": "M06", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_9"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "现场表演念白", "mc_file": "", "link": ""}, {"num": "M07", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_4"}, {"num": "M08", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931167_4"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "现场表演念白", "mc_file": "", "link": ""}, {"num": "", "title": "Bass Solo", "highlight_label": "Solo", "highlight_text": "", "mc_file": "", "link": ""}, {"num": "M09", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_5"}, {"num": "M10", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_4"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "现场表演念白", "mc_file": "", "link": ""}, {"num": "M11", "title": "Symbol III : 🜄", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965_3"}, {"num": "M12", "title": "Symbol IV : 🜃", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934854_3"}, {"num": "M14", "title": "Ether", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933636_3"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP01", "mc_file": "", "link": ""}, {"num": "M14", "title": "KiLLKiSS", "highlight_label": "Unreleased Song", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379"}],
    backstage: []
  },
  {
    name: "リスアニ!LIVE 2025 SATURDAY STAGE",
    hash_id: "nYzdhO9k4Qt",
    date: "2025/1/25",
    venue: "日本武道館",
    tag: "Fes",
    poster: "../images/logo/lisani2025logo.webp",
    kv: "../images/lisani2025_am01.webp",
    video_url: "https://www.bilibili.com/video/BV1aAZYYAEEQ",
    description: "非全场",
    for_short: "Lisani 2025",
    setlist: [{"num": "M01", "title": "Georgette Me, Georgette You", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47924476"}, {"num": "M02", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_6"}, {"num": "M05", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_2"}],
    backstage: [{"photo": "../images/lisani2025_am02.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am03.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am04.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am05.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am06.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am07.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am08.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am09.webp", "credit": "@LISANI", "credit_text": "lisani LIVE返图", "source_url": "https://www.lisani.jp/0000274982/", "source_label": "", "group_id": "lisani全员"}, {"photo": "../images/lisani2025_am01.webp", "credit": "@LISANI", "credit_text": "lisani 官方宣传图", "source_url": "https://x.com/Lis_Ani/status/1882697370993098886", "source_label": "", "group_id": "lisani全员-2"}, {"photo": "../images/lisani2025_am10.webp", "credit": "@LISANI", "credit_text": "lisani 官方宣传图", "source_url": "https://x.com/Lis_Ani/status/1883066548900024440", "source_label": "", "group_id": "lisani全员-2"}]
  },
  {
    name: "Ave Mujica「KiLLKiSS」購入者限定フリーライブ",
    hash_id: "GAHzTYijlb4",
    date: "2025/2/2",
    venue: "KT Zepp Yokohama",
    tag: "One Man Live",
    poster: "../images/logo/kkfreelivelogo.webp",
    kv: "../images/kkfreelive kv.webp",
    video_url: "https://www.bilibili.com/video/BV19nfKYfEAd",
    description: "",
    for_short: "free live",
    setlist: [{"num": "M01", "title": "KiLLKiSS", "highlight_label": "Highlight", "highlight_text": "起始与终结重复两次的KiLLKiSS", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_3"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_5"}, {"num": "M03", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934758_10"}, {"num": "M04", "title": "黒のバースデイ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_6"}, {"num": "M05", "title": "Angles", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931167_5"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M06", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_5"}, {"num": "M07", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_6"}, {"num": "M08", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_7"}, {"num": "M09", "title": "Symbol III : 🜄", "highlight_label": "Live Arrangement", "highlight_text": "无弦乐", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965_4"}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "M10", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_8"}, {"num": "M11", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_7"}, {"num": "M12", "title": "Georgette Me, Georgette You", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47924476_2"}, {"num": "M13", "title": "KiLLKiSS", "highlight_label": "Highlight", "highlight_text": "起始与终结重复两次的KiLLKiSS", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_4"}],
    backstage: []
  },
  {
    name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」DAY1 : Petrichor",
    hash_id: "yNNdfPu4f4B",
    date: "2025/4/26",
    venue: "Kアリーナ横浜",
    tag: "BanG Dream!",
    poster: "../images/logo/鸡狗1d1logo.webp",
    kv: "../images/鸡狗1横k kv.webp",
    video_url: "https://www.bilibili.com/video/BV1RV2eBeEAd",
    description: "「分歧路口，前路漫漫」横K场",
    for_short: "MyMuji1 横KD1",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "Anime", "highlight_text": "「BanG Dream! It's MyGO!!!!!」EP13", "mc_file": "", "link": ""}, {"num": "M01", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_5"}, {"num": "M02", "title": "Georgette Me, Georgette You", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47924476_3"}, {"num": "M03", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934815"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP01", "mc_file": "", "link": ""}, {"num": "", "title": "Interlude", "highlight_label": "theatrical segment", "highlight_text": "还原「BanG Dream! Ave Mujica」EP01的预录音轨演出", "mc_file": "", "link": ""}, {"num": "", "title": "Interlude", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP10", "mc_file": "", "link": ""}, {"num": "M04", "title": "Imprisoned XII", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931260"}, {"num": "M05", "title": "Crucifix X", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208"}, {"num": "M06", "title": "八芒星ダンス", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931830"}, {"num": "M07", "title": "顔", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP13", "mc_file": "", "link": ""}, {"num": "M08", "title": "天球（そら）のMúsica", "highlight_label": "Live debut", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932123"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP13", "mc_file": "", "link": ""}, {"num": "", "title": "MC", "highlight_label": "Highlight", "highlight_text": "首次MC", "mc_file": "", "link": ""}],
    backstage: []
  },
  {
    name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」DAY2 : Geosmin",
    hash_id: "ZY6XWwgiPC7",
    date: "2025/4/27",
    venue: "Kアリーナ横浜",
    tag: "BanG Dream!",
    poster: "../images/logo/鸡狗1d2logo.webp",
    kv: "../images/鸡狗1横k kv.webp",
    video_url: "https://www.acfun.cn/v/ac48829435",
    description: "「分歧路口，前路漫漫」横K场",
    for_short: "MyMuji1 横KD2",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "Monologues", "highlight_text": "预录念白", "mc_file": "", "link": ""}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP13", "mc_file": "", "link": ""}, {"num": "M01", "title": "Imprisoned XII", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931260_2"}, {"num": "M02", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934815_2"}, {"num": "M03", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_2"}, {"num": "M04", "title": "天球（そら）のMúsica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932123_2"}, {"num": "", "title": "Interlude", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP13", "mc_file": "", "link": ""}, {"num": "M05", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_6"}, {"num": "M06", "title": "Crucifix X", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208_2"}, {"num": "M07", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931830_2"}, {"num": "M08", "title": "Georgette Me, Georgette You", "highlight_label": "Highlight", "highlight_text": "A melo不进", "mc_file": "", "link": "https://www.acfun.cn/v/ac47924476_4"}, {"num": "", "title": "MC", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": ""}],
    backstage: []
  },
  {
    name: "JAPAN JAM 2025",
    hash_id: "FjhiWd71PiS",
    date: "2025/5/5",
    venue: "千葉市蘇我スポーツ公園",
    tag: "Fes",
    poster: "../images/logo/japanjam2025logo.webp",
    kv: "../images/japanjam2025 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1pB3izpExm",
    description: "非全场",
    for_short: "JJ2025",
    setlist: [{"num": "M01", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "Georgette Me, Georgette You", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M05", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_8"}],
    backstage: []
  },
  {
    name: "ANISAMA WORLD 2025 in MANILA",
    hash_id: "4TL4Z9kaPRf",
    date: "2025/6/7",
    venue: "Smart Araneta Coliseum",
    tag: "Fes",
    poster: "../images/logo/asl2025manlialogo.webp",
    kv: "../images/asl2025manlia kv.webp",
    video_url: "",
    description: "",
    for_short: "ASL2025 马尼拉",
    setlist: [{"num": "M01", "title": "Georgette Me, Georgette You", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "BILIBILI MACRO LINK 2025 DAY2",
    hash_id: "u8D164bh4Qj",
    date: "2025/7/12",
    venue: "国家会展中心（上海）虹馆EH",
    tag: "Fes",
    poster: "../images/logo/bml2025d2logo.webp",
    kv: "../images/bml2025 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1Ac8yzxERF",
    description: "非全场",
    for_short: "BML2025 D2",
    setlist: [{"num": "M01", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_7"}, {"num": "M02", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Imprisoned XII", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "BILIBILI MACRO LINK 2025 DAY3",
    hash_id: "degh8ZwDaQA",
    date: "2025/7/13",
    venue: "国家会展中心（上海）虹馆EH",
    tag: "Fes",
    poster: "../images/logo/bml2025d3logo.webp",
    kv: "../images/bml2025 kv.webp",
    video_url: "",
    description: "非全场",
    for_short: "BML2025 D3",
    setlist: [{"num": "M01", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "天球（そら）のMúsica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "Ave Mujica 5th LIVE「Nova Historia」DAY1",
    hash_id: "Yo2h7VNdBuH",
    date: "2025/7/26",
    venue: "LaLa arena TOKYO-BAY",
    tag: "One Man Live",
    poster: "../images/logo/5thd1logo.webp",
    kv: "../images/5th kv.webp",
    video_url: "https://www.bilibili.com/video/BV1w9q8BJEzM",
    description: "「新的历史」",
    for_short: "5th D1",
    setlist: [{"num": "M00", "title": "贝多芬「月光奏鸣曲」第一乐章", "highlight_label": "Solo", "highlight_text": "三角钢琴", "mc_file": "", "link": ""}, {"num": "M01", "title": "Crucifix X", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208_3"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_6"}, {"num": "M03", "title": "DIVINE", "highlight_label": "Live debut", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930865"}, {"num": "M04", "title": "Ether", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933636_4"}, {"num": "M05", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934815_3"}, {"num": "M06", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_7"}, {"num": "M07", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_6"}, {"num": "M08", "title": "黒のバースデイ", "highlight_label": "Live Arrangement", "highlight_text": "结尾念白改编", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_7"}, {"num": "M09", "title": "Symbol IV : 🜃", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934854_4"}, {"num": "", "title": "Piano Solo", "highlight_label": "Solo", "highlight_text": "肖邦练习曲Op.10改编", "mc_file": "", "link": ""}, {"num": "M10", "title": "Symbol III : 🜄", "highlight_label": "Live Arrangement", "highlight_text": "无弦乐，自由速度", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965_5"}, {"num": "M11", "title": "天球（そら）のMúsica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932123_3"}, {"num": "M12", "title": "Imprisoned XII", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931260_3"}, {"num": "M13", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "Live Arrangement", "highlight_text": "开场清唱", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_9"}, {"num": "M14", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931830_3"}, {"num": "M15", "title": "'S/' The Way", "highlight_label": "Unreleased Song", "highlight_text": "表记「？？？？？」", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930836"}, {"num": "M16", "title": "顔", "highlight_label": "Live Arrangement", "highlight_text": "Doloris未演奏主音吉他", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_3"}, {"num": "M17", "title": "KiLLKiSS", "highlight_label": "Live Arrangement", "highlight_text": "intro cut 与「顔」构成Non-stop", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_8"}, {"num": "M18", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_9"}],
    backstage: []
  },
  {
    name: "Ave Mujica 5th LIVE「Nova Historia」DAY2",
    hash_id: "HK5tJ9ottPW",
    date: "2025/7/27",
    venue: "LaLa arena TOKYO-BAY",
    tag: "One Man Live",
    poster: "../images/logo/5thd2logo.webp",
    kv: "../images/5th kv.webp",
    video_url: "https://www.bilibili.com/video/BV19Aus6SEqj",
    description: "「新的历史」",
    for_short: "5th D2",
    setlist: [{"num": "M00", "title": "贝多芬「月光奏鸣曲」第一乐章", "highlight_label": "Solo", "highlight_text": "三角钢琴", "mc_file": "", "link": ""}, {"num": "M01", "title": "Crucifix X", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208_4"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_7"}, {"num": "M03", "title": "DIVINE", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930865_2"}, {"num": "M04", "title": "Ether", "highlight_label": "Highlight", "highlight_text": "三角钢琴", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933636_5"}, {"num": "M05", "title": "Ave Mujica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934815_4"}, {"num": "M06", "title": "Choir 'S' Choir", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935101_8"}, {"num": "M07", "title": "素晴らしき世界 でも どこにもない場所", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933675_7"}, {"num": "M08", "title": "黒のバースデイ", "highlight_label": "Live Arrangement", "highlight_text": "结尾念白改编", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932539_8"}, {"num": "M09", "title": "Symbol IV : 🜃", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934854_5"}, {"num": "", "title": "Piano Solo", "highlight_label": "Solo", "highlight_text": "肖邦练习曲Op.10改编", "mc_file": "", "link": ""}, {"num": "M10", "title": "Symbol III : 🜄", "highlight_label": "Live Arrangement", "highlight_text": "无弦乐，自由速度，超长停止", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930965_6"}, {"num": "M11", "title": "天球（そら）のMúsica", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932123_4"}, {"num": "M12", "title": "Imprisoned XII", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931260_4"}, {"num": "M13", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "Live Arrangement", "highlight_text": "开场清唱", "mc_file": "", "link": "https://www.acfun.cn/v/ac47935303_10"}, {"num": "M14", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931830_4"}, {"num": "M15", "title": "'S/' The Way", "highlight_label": "Highlight", "highlight_text": "表记「？？？？？」", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930836_2"}, {"num": "M16", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_4"}, {"num": "M17", "title": "KiLLKiSS", "highlight_label": "Live Arrangement", "highlight_text": "intro cut 与「顔」构成Non-stop", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_9"}, {"num": "M18", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931569_10"}],
    backstage: []
  },
  {
    name: "SUMMER SONIC 2025 TOKYO",
    hash_id: "HHUDwtdo0o9",
    date: "2025/8/16",
    venue: "ZOZOマリンスタジアム＆幕張メッセ",
    tag: "Fes",
    poster: "../images/logo/ss2025logo.webp",
    kv: "../images/ss2025 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1F9YYzwESD",
    description: "",
    for_short: "SS2025",
    setlist: [{"num": "", "title": "Piano Solo", "highlight_label": "Solo", "highlight_text": "拉威尔「悼念公主的帕凡舞曲」", "mc_file": "", "link": ""}, {"num": "M01", "title": "'S/' The Way", "highlight_label": "Highlight", "highlight_text": "表记「？？？？？」", "mc_file": "", "link": "https://www.acfun.cn/v/ac47930836_3"}, {"num": "M02", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47933063_8"}, {"num": "M03", "title": "神さま、バカ", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47934950_8"}, {"num": "M04", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_5"}, {"num": "M05", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932379_10"}, {"num": "M06", "title": "Symbol I : 🜂", "highlight_label": "Highlight", "highlight_text": "主音吉他器材事故 Doloris救场处理", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931603"}],
    backstage: []
  },
  {
    name: "Animelo Summer Live 2025 “ThanXX!”",
    hash_id: "BIA7gtRausC",
    date: "2025/8/30",
    venue: "さいたまスーパーアリーナ",
    tag: "Fes",
    poster: "../images/logo/asl2025logo.webp",
    kv: "../images/asl2025 kv.webp",
    video_url: "https://www.acfun.cn/v/ac48796328",
    description: "",
    for_short: "ASL2025",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "Anime", "highlight_text": "「BanG Dream! Ave Mujica」EP13", "mc_file": "", "link": ""}, {"num": "M01", "title": "KiLLKiSS", "highlight_label": "Highlight", "highlight_text": "intro还原动画台词", "mc_file": "", "link": "https://www.acfun.cn/v/ac48055738"}, {"num": "M02", "title": "Crucifix X", "highlight_label": "Highlight", "highlight_text": "intro还原动画台词", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208_5"}, {"num": "M03", "title": "八芒星ダンス", "highlight_label": "Highlight", "highlight_text": "Ainme ver", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931830_5"}, {"num": "M04", "title": "顔", "highlight_label": "Highlight", "highlight_text": "intro改编 与观众互动", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_6"}, {"num": "M05", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Doloris from Ave Mujica with angela", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931710_4"}],
    backstage: []
  },
  {
    name: "rockin'on presents ROCK IN JAPAN FESTIVAL 2025",
    hash_id: "PpX59bZxUv1",
    date: "2025/9/20",
    venue: "千葉市蘇我スポーツ公園",
    tag: "Fes",
    poster: "../images/logo/rockinjapan2025logo.webp",
    kv: "../images/rockinjapan2025 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1CZUfBtEWF",
    description: "",
    for_short: "RIJ2025",
    setlist: [{"num": "M01", "title": "DIVINE", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "'S/' The Way", "highlight_label": "Highlight", "highlight_text": "表记「？？？？？」", "mc_file": "", "link": "0"}, {"num": "M04", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931318_7"}, {"num": "M05", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48055738_2"}, {"num": "M06", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: []
  },
  {
    name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」上海追加公演 DAY1 : Petrichor",
    hash_id: "jfgTjcYZTf4",
    date: "2025/10/11",
    venue: "梅赛德斯-奔驰文化中心 （Mercedes-Benz Arena）",
    tag: "BanG Dream!",
    poster: "../images/logo/鸡狗1上海d1logo.webp",
    kv: "../images/鸡狗1上海 kv.webp",
    video_url: "https://www.bilibili.com/video/BV19Y3g6SEqY",
    description: "「分歧路口，前路漫漫」梅奔场",
    for_short: "MyMuji1 梅奔D1",
    setlist: [],
    backstage: []
  },
  {
    name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」上海追加公演 DAY2 : Geosmin",
    hash_id: "u7cOTddR25p",
    date: "2025/10/12",
    venue: "梅赛德斯-奔驰文化中心 （Mercedes-Benz Arena）",
    tag: "BanG Dream!",
    poster: "../images/logo/鸡狗1上海d2logo.webp",
    kv: "../images/鸡狗1上海 kv.webp",
    video_url: "https://www.bilibili.com/video/BV19Y3g6SEqY/?p=2",
    description: "「分歧路口，前路漫漫」梅奔场",
    for_short: "MyMuji1 梅奔D2",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演",
    hash_id: "nCXrA7Gboon",
    date: "2025/12/14",
    venue: "東京国際フォーラム ホールA",
    tag: "One Man Live",
    poster: "../images/logo/6th东京logo.webp",
    kv: "../images/6th kv.webp",
    video_url: "https://www.bilibili.com/video/BV1CvuJ6pEqS",
    description: "「继续前行」",
    for_short: "6th 东京",
    setlist: [],
    backstage: []
  },
  {
    name: "ABEMA 日本アニメトレンド大賞 2025",
    hash_id: "eA2fQEa9K5J",
    date: "2025/12/26",
    venue: "Studio",
    tag: "Fes",
    poster: "../images/logo/abemaanison大赏2025logo.webp",
    kv: "../images/abemaanison大赏2025 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1LmBvBQEag",
    description: "",
    for_short: "ABEMA",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演",
    hash_id: "7JzNza1WvDh",
    date: "2026/1/15",
    venue: "グランキューブ大阪 メインホール",
    tag: "One Man Live",
    poster: "../images/logo/6th大阪logo.webp",
    kv: "../images/6th kv.webp",
    video_url: "",
    description: "「继续前行」",
    for_short: "6th 大阪",
    setlist: [],
    backstage: []
  },
  {
    name: "BanG Dream! 10th Anniversary LIVE「In the name of BanG Dream!」",
    hash_id: "aVUA8584b3D",
    date: "2026/2/28",
    venue: "Kアリーナ横浜",
    tag: "BanG Dream!",
    poster: "../images/logo/邦邦10周年logo.webp",
    kv: "../images/邦邦10周年 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1rfdVB1EW9",
    description: "「以BanG Dream!之名」",
    for_short: "邦10周年",
    setlist: [],
    backstage: []
  },
  {
    name: "MyGO!!!!!×Ave Mujica ツーマンライブ「“moment / memory”」",
    hash_id: "gCQKj5kbxk3",
    date: "2026/3/1",
    venue: "Kアリーナ横浜",
    tag: "BanG Dream!",
    poster: "../images/logo/横k鸡狗2logo.webp",
    kv: "../images/横k鸡狗2 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1TFJW6FEeP",
    description: "「“瞬间 / 记忆”」",
    for_short: "MyMuji2 横K",
    setlist: [],
    backstage: []
  },
  {
    name: "MEGA VEGAS 2026",
    hash_id: "CzfNqgGp7u2",
    date: "2026/3/20",
    venue: "神戸ワールド記念ホール",
    tag: "Fes",
    poster: "../images/logo/megavegas2026logo.webp",
    kv: "../images/megavegas2026 kv.webp",
    video_url: "",
    description: "",
    for_short: "MEGA VEGAS 2026",
    setlist: [],
    backstage: []
  },
  {
    name: "CENTRAL MUSIC & ENTERTAINMENT FESTIVAL 2026",
    hash_id: "5ABzW9qB3dO",
    date: "2026/4/4",
    venue: "KT Zepp Yokohama",
    tag: "Fes",
    poster: "../images/logo/central2026logo.webp",
    kv: "../images/central26 kv.webp",
    video_url: "https://www.bilibili.com/video/BV18RdHBnELz",
    description: "",
    for_short: "CENTRAL 2026",
    setlist: [],
    backstage: []
  },
  {
    name: "BanG Dream! Special LIVE in TAIPEI DAY1 : MyGO!!!!!×Ave Mujica「\"moment / memory\"」",
    hash_id: "1FV5SUvHggy",
    date: "2026/4/11",
    venue: "台北・大佳河濱公園",
    tag: "BanG Dream!",
    poster: "../images/logo/台北鸡狗2logo.webp",
    kv: "../images/台北鸡狗2 kv.webp",
    video_url: "",
    description: "「“瞬间 / 记忆”」",
    for_short: "MyMuji2 台北",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」福冈公演",
    hash_id: "SN8jSKTclRt",
    date: "2026/4/17",
    venue: "Zepp Fukuoka",
    tag: "One Man Live",
    poster: "../images/logo/exitus福冈logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 福冈",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」大阪公演",
    hash_id: "je7GMFTN4JR",
    date: "2026/4/26",
    venue: "Zepp Namba",
    tag: "One Man Live",
    poster: "../images/logo/exitus大阪logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 大阪",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」爱知公演",
    hash_id: "BRY81XgYdRL",
    date: "2026/5/1",
    venue: "Zepp Nagoya",
    tag: "One Man Live",
    poster: "../images/logo/exitus爱知logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 爱知",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」东京公演",
    hash_id: "tTZFJQohWCn",
    date: "2026/5/4",
    venue: "Zepp Haneda (TOKYO)",
    tag: "One Man Live",
    poster: "../images/logo/exitus东京logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 羽田",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY1",
    hash_id: "jW70ATvaZuV",
    date: "2026/6/19",
    venue: "SGC HALL ARIAKE",
    tag: "One Man Live",
    poster: "../images/logo/exitusfld1logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "https://www.bilibili.com/video/BV1xRuR64Eqs",
    description: "「出口」",
    for_short: "Exitus FLD1",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2",
    hash_id: "NTQrfXPOAaM",
    date: "2026/6/20",
    venue: "SGC HALL ARIAKE",
    tag: "One Man Live",
    poster: "../images/logo/exitusfld2logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "https://www.bilibili.com/video/BV1h4hA6gEGe",
    description: "「出口」",
    for_short: "Exitus FLD2",
    setlist: [],
    backstage: []
  },
  {
    name: "BEAT AX -SUMMER EDITION 2026-",
    hash_id: "Lrb1xakoKhU",
    date: "2026/7/12",
    venue: "Kアリーナ横浜",
    tag: "Fes",
    poster: "../images/logo/beatax2026logo.webp",
    kv: "../images/beatax2026 kv.webp",
    video_url: "",
    description: "",
    for_short: "BEAT AX 2026",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY1",
    hash_id: "ZpjdS8wLLvC",
    date: "2026/8/8",
    venue: "國立體育大學綜合體育館（林口體育館）",
    tag: "One Man Live",
    poster: "../images/logo/exitus台北d1logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 台北D1",
    setlist: [],
    backstage: []
  },
  {
    name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY2",
    hash_id: "rBpIqAXDMLv",
    date: "2026/8/9",
    venue: "國立體育大學綜合體育館（林口體育館）",
    tag: "One Man Live",
    poster: "../images/logo/exitus台北d2logo.webp",
    kv: "../images/exitus kv.webp",
    video_url: "",
    description: "「出口」",
    for_short: "Exitus 台北D2",
    setlist: [],
    backstage: []
  },
  {
    name: "SUMMER SONIC 2026 OSAKA",
    hash_id: "PaLBMLHmpMR",
    date: "2026/8/14",
    venue: "万博記念公園",
    tag: "Fes",
    poster: "../images/logo/ss2026大阪logo.webp",
    kv: "../images/ss2026 kv.webp",
    video_url: "",
    description: "",
    for_short: "SS2026大阪",
    setlist: [{"num": "M01", "title": "Crucifix X", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M02", "title": "Sophie", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M03", "title": "Georgette Me, Georgette You", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M04", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M05", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M06", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M07", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M08", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}, {"num": "M09", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "0"}],
    backstage: [{"photo": "../images/ss26_osaka_bang01.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/bang_dream_info/status/2088182616268910792?s=20", "source_label": "yes", "group_id": ""}, {"photo": "../images/ss26_osaka_am01.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am02.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am03.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am04.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am05.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am06.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am07.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am08.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am09.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am10.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_am11.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/2026live/detail/ave-mujica-2/#galleryMain", "source_label": "yes", "group_id": "ss大阪ss官方返图"}, {"photo": "../images/ss26_osaka_wts01.webp", "credit": "Mortis", "credit_text": "把酷暑也一并卷入，拼尽全力", "source_url": "https://x.com/Watase_Yuzuki/status/2088065379088347150?s=20", "source_label": "yes", "group_id": "ss大阪结月"}, {"photo": "../images/ss26_osaka_wts02.webp", "credit": "Mortis", "credit_text": "超——级热超级火热 谢谢🔥🤘 Gt. Mortis", "source_url": "https://x.com/Watase_Yuzuki/status/2088179201157537898?s=20", "source_label": "yes", "group_id": "ss大阪结月"}, {"photo": "../images/ss26_osaka_wts03.webp", "credit": "Mortis", "credit_text": "©SUMMER SONIC All Rights Reserved.", "source_url": "https://x.com/Watase_Yuzuki/status/2088786673832538180?s=20", "source_label": "yes", "group_id": "ss大阪结月"}, {"photo": "../images/ss26_osaka_rico01.webp", "credit": "Doloris", "credit_text": "把一切献给METAL。。🤘", "source_url": "https://x.com/sasakirico/status/2087837294204240082?s=20", "source_label": "yes", "group_id": "ss大阪李子"}, {"photo": "../images/ss26_osaka_rico02.webp", "credit": "Doloris", "credit_text": "👁️", "source_url": "https://x.com/sasakirico/status/2088071499219644718?s=20", "source_label": "yes", "group_id": "ss大阪李子"}, {"photo": "../images/ss26_osaka_rico03.webp", "credit": "Doloris", "credit_text": "Thanks!!!!!!!!!!\nAve Mujica Gt.&Vo. Doloris", "source_url": "https://x.com/sasakirico/status/2088175045470458281?s=20", "source_label": "yes", "group_id": "ss大阪李子"}, {"photo": "../images/ss26_osaka_rico04.webp", "credit": "Doloris", "credit_text": "©SUMMER SONIC All Rights Reserved.\n凝视深渊。\nAve Mujica Gt.&Vo. Doloris", "source_url": "https://x.com/sasakirico/status/2088789235675627903?s=20", "source_label": "yes", "group_id": "ss大阪李子"}, {"photo": "../images/ss26_osaka_okd01.webp", "credit": "Timoris", "credit_text": "请多关照 ☪️🎸🐺⋆✦", "source_url": "https://x.com/okada_mei0519/status/2088073610279976970?s=20", "source_label": "yes", "group_id": "ss大阪梦以"}, {"photo": "../images/ss26_osaka_okd02.webp", "credit": "Timoris", "credit_text": "大阪，真是最棒的时光\n非常感谢🎪🔥⋆✦\nAve Mujica ☪︎ Ba. Timoris 🎸🐺·̩͙", "source_url": "https://x.com/okada_mei0519/status/2088196024183706065?s=20", "source_label": "yes", "group_id": "ss大阪梦以"}, {"photo": "../images/ss26_osaka_okd03.webp", "credit": "Timoris", "credit_text": "早上好 🎸🐺🔥⋆✦", "source_url": "https://x.com/okada_mei0519/status/2088788020396998908?s=20", "source_label": "yes", "group_id": "ss大阪梦以"}, {"photo": "../images/ss26_osaka_akn01.webp", "credit": "Amoris", "credit_text": "作为Ave Mujica的鼓手，我将献上一切全力击鼓。", "source_url": "https://x.com/AkaneY_banu/status/2087805197519315389?s=20", "source_label": "yes", "group_id": "ss大阪茜"}, {"photo": "../images/ss26_osaka_akn02.webp", "credit": "Amoris", "credit_text": "Thank youuu❤️‍🔥🥁🫶", "source_url": "https://x.com/AkaneY_banu/status/2088166403216113908?s=20", "source_label": "yes", "group_id": "ss大阪茜"}, {"photo": "../images/ss26_osaka_akn03.webp", "credit": "Amoris", "credit_text": "Let’s gooo✋🏻👩🏻🤚🏻🥁🔥", "source_url": "https://x.com/AkaneY_banu/status/2088776461314658317?s=20", "source_label": "yes", "group_id": "ss大阪茜"}, {"photo": "../images/ss26_osaka_akn04.webp", "credit": "Amoris", "credit_text": "", "source_url": "https://www.instagram.com/p/DcKz4TiIKnr/?igsi=MWF2bTdnNXFyNXNybg==", "source_label": "yes", "group_id": "ss大阪茜"}, {"photo": "../images/ss26_osaka_nn01.webp", "credit": "Oblivionis", "credit_text": "要上咯！！！！！🤘", "source_url": "https://x.com/Kanon_Takao/status/2088068841750577436?s=20", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn02.webp", "credit": "Oblivionis", "credit_text": "谢谢！！！！！❤️‍🔥🤘\nAve Mujica  Key.Oblibionis 🎹", "source_url": "https://x.com/Kanon_Takao/status/2088179763735396687?s=20", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn03.webp", "credit": "Oblivionis", "credit_text": "©SUMMER SONIC All Rights Reserved. \n❤️‍🔥🎹🌙", "source_url": "https://x.com/Kanon_Takao/status/2088627188316930108?s=20", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn04.webp", "credit": "Oblivionis", "credit_text": "©SUMMER SONIC All Rights Reserved. \n今天…⚙️\nAve Mujica Key. Oblivionis 🎹🌙", "source_url": "https://x.com/Kanon_Takao/status/2088823105057853755?s=20", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn05.webp", "credit": "Oblivionis", "credit_text": "", "source_url": "https://www.instagram.com/p/DcGopDjj59f/?img_index=6&igsi=c20wcmhuZjg3cHhr", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn06.webp", "credit": "Oblivionis", "credit_text": "", "source_url": "https://www.instagram.com/p/DcGopDjj59f/?img_index=6&igsi=c20wcmhuZjg3cHhr", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn07.webp", "credit": "Oblivionis", "credit_text": "", "source_url": "https://www.instagram.com/p/DcGopDjj59f/?img_index=6&igsi=c20wcmhuZjg3cHhr", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn08.webp", "credit": "Oblivionis", "credit_text": "", "source_url": "https://www.instagram.com/p/DcGopDjj59f/?img_index=6&igsi=c20wcmhuZjg3cHhr", "source_label": "yes", "group_id": "ss大阪弄"}, {"photo": "../images/ss26_osaka_nn09.webp", "credit": "Oblivionis", "credit_text": "", "source_url": "https://www.instagram.com/p/DcGopDjj59f/?img_index=6&igsi=c20wcmhuZjg3cHhr", "source_label": "yes", "group_id": "ss大阪弄"}]
  },
  {
    name: "SUMMER SONIC 2026 TOKYO",
    hash_id: "3nFOdwiBjfR",
    date: "2026/8/16",
    venue: "ZOZOマリンスタジアム＆幕張メッセ",
    tag: "Fes",
    poster: "../images/logo/ss2026东京logo.webp",
    kv: "../images/ss2026 kv.webp",
    video_url: "https://www.bilibili.com/video/BV1zPbR6FEo3/",
    description: "",
    for_short: "SS2026东京",
    setlist: [{"num": "M01", "title": "Crucifix X", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47932208_10"}, {"num": "M02", "title": "Sophie", "highlight_label": "Highlight", "highlight_text": "尖叫部分使用极端嗓", "mc_file": "", "link": "https://www.acfun.cn/v/ac48115972_7"}, {"num": "M03", "title": "Georgette Me, Georgette You", "highlight_label": "Live Arrangement", "highlight_text": "慢版Arrangement", "mc_file": "", "link": "https://www.acfun.cn/v/ac47924476_8"}, {"num": "M04", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48116488_5"}, {"num": "M05", "title": "八芒星ダンス", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48751840_3"}, {"num": "M06", "title": "Symbol II : 🜁", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48409409_4"}, {"num": "M07", "title": "顔", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48311717_7"}, {"num": "M08", "title": "KiLLKiSS", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac48751334_3"}, {"num": "M09", "title": "Symbol I : 🜂", "highlight_label": "", "highlight_text": "", "mc_file": "", "link": "https://www.acfun.cn/v/ac47931603_8"}],
    backstage: [{"photo": "../images/ss26_tokyo_bang01.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/bang_dream_info/status/2088892974197617058?s=20", "source_label": "yes", "group_id": ""}, {"photo": "../images/ss26_metal01.webp", "credit": "@BABYMETAL_JAPAN", "credit_text": "BABYMETAL返图", "source_url": "https://x.com/BABYMETAL_JAPAN/status/2089290445172125822?s=20", "source_label": "yes", "group_id": ""}, {"photo": "../images/ss26_metal02.webp", "credit": "@RollingStoneJapan", "credit_text": "RollingStoneJapan访谈返图", "source_url": "https://rollingstonejapan.com/articles/detail/45248", "source_label": "yes", "group_id": "ss东京滚石"}, {"photo": "../images/ss26_metal03.webp", "credit": "@RollingStoneJapan", "credit_text": "RollingStoneJapan访谈返图", "source_url": "https://rollingstonejapan.com/articles/detail/45248", "source_label": "yes", "group_id": "ss东京滚石"}, {"photo": "../images/ss26_tokyo_am01.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am02.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am03.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am04.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am05.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am06.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am07.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am08.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am09.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am10.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_am11.webp", "credit": "Summer Sonic", "credit_text": "Summer Sonic 官方返图", "source_url": "https://www.summersonic.com/en/2026live/detail/ave-mujica/", "source_label": "yes", "group_id": "ss东京ss官方返图"}, {"photo": "../images/ss26_tokyo_wts01.webp", "credit": "Mortis", "credit_text": "大家最!棒!!!!!!!!!!!!!!!!!!!!!\nThanks!!!!!!!!!!!!!", "source_url": "https://x.com/Watase_Yuzuki/status/2088894872896061845?s=20", "source_label": "yes", "group_id": "ss东京结月"}, {"photo": "../images/ss26_tokyo_wts02.webp", "credit": "Mortis", "credit_text": "mortis", "source_url": "https://x.com/Watase_Yuzuki/status/2089309227349320029?s=20", "source_label": "yes", "group_id": "ss东京结月"}, {"photo": "../images/ss26_tokyo_rico.webp", "credit": "Doloris", "credit_text": "METAL！！！！！！\n🤘🤘🤘🔥🔥🔥\nAve Mujica Gt.&Vo. Doloris", "source_url": "https://x.com/sasakirico/status/2088912851788599553?s=20", "source_label": "yes", "group_id": ""}, {"photo": "../images/ss26_tokyo_okd.webp", "credit": "Timoris", "credit_text": "太棒了…🌙🔥非常感谢⋆✦Ave Mujica ☪︎  Ba. Timoris 🎸🐺·", "source_url": "https://x.com/okada_mei0519/status/2088915247579247066?s=20", "source_label": "yes", "group_id": ""}, {"photo": "../images/ss26_tokyo_akn01.webp", "credit": "Amoris", "credit_text": "Thank you❤️🥁", "source_url": "https://x.com/AkaneY_banu/status/2088959677946302697?s=20", "source_label": "yes", "group_id": "ss东京茜"}, {"photo": "../images/ss26_tokyo_akn02.webp", "credit": "Amoris", "credit_text": "", "source_url": "https://x.com/AkaneY_banu/status/2088971771043250400?s=20", "source_label": "yes", "group_id": "ss东京茜"}, {"photo": "../images/ss26_tokyo_akn03.webp", "credit": "Amoris", "credit_text": "🦊🥁", "source_url": "https://x.com/AkaneY_banu/status/2090331116557455635?s=20", "source_label": "yes", "group_id": "ss东京茜"}, {"photo": "../images/ss26_tokyo_nn01.webp", "credit": "Oblivionis", "credit_text": "非常感谢…！！！🌙⚙️\n最棒！！！🤘❤️‍🔥\nAve Mujica Key. Oblivionis🎹💠", "source_url": "https://x.com/Kanon_Takao/status/2088894417797296397?s=20", "source_label": "yes", "group_id": "ss东京弄弄"}, {"photo": "../images/ss26_tokyo_nn02.webp", "credit": "Oblivionis", "credit_text": "非常感谢…！！！🌙⚙️\n最棒！！！🤘❤️‍🔥\nAve Mujica Key. Oblivionis🎹💠", "source_url": "https://x.com/Kanon_Takao/status/2088894417797296397?s=20", "source_label": "yes", "group_id": "ss东京弄弄"}, {"photo": "../images/ss26_tokyo_nn03.webp", "credit": "Oblivionis", "credit_text": "©SUMMER SONIC All Rights Reserved.\n渐燃而上…… 🔥🎹", "source_url": "https://x.com/Kanon_Takao/status/2089235321276027276?s=20", "source_label": "yes", "group_id": "ss东京弄弄"}]
  }
];
