// 演唱会数据
// 由 generate_data.py 自动生成，请勿手动修改
// 编辑 data.xlsx 后运行「一键更新数据.bat」即可更新

const livesData = [
  {
    name: "Ave Mujica 0th LIVE「Primo die in scaena」",
    date: "2023/6/4",
    venue: "中野サンプラザホール",
    poster: "../images/0th.webp",
    kv: "../images/0th kv假.webp",
    video_url: "https://www.bilibili.com/video/BV1QsnXzBEWb/",
    description: "「初次登台」",
    setlist: [{"num": "", "title": "Intro", "highlight_label": "", "highlight_text": "", "mc_file": "mc/0_0.md", "mc_content": "舞台暗転。5人のシルエットが浮かび上がる。\n\n**[c1]Doloris：[/c1]**\n「私は…私を見つけるために、ここに来た。」\n\nMortis:\n「仮面の下に隠した、本当の自分を」\n\nTimoris:\n「誰にも見せられなかった、弱さも」\n\nAmoris:\n「誰にも言えなかった、叫びも」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\nOblivionis:\n「――すべてを、ここに」\n\n---\n\n**灯光渐暗，五人的剪影浮现。**\n\n[c1]Doloris：[/c1]\n「我……是为了找到真正的自己，才来到这里的。」\n\nMortis：\n「隐藏在面具之下的、真正的自我」\n\nTimoris：\n「无法示人的脆弱」\n\nAmoris：\n「无法说出口的呐喊」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」\n\nOblivionis：\n「——将这一切，在此处」"}, {"num": "M01", "title": "黒のバースデイ", "highlight_label": "Live debut", "highlight_text": "", "mc_file": ""}, {"num": "M02", "title": "KINGS", "highlight_label": "COVER", "highlight_text": "Originally by angela 「K」OP", "mc_file": ""}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "ホントウノワタシ -再生-“真正的我”", "mc_file": ""}, {"num": "M03", "title": "ふたつの月 ~Deep Into The Forest~", "highlight_label": "Live debut", "highlight_text": "", "mc_file": ""}, {"num": "M04", "title": "暗黒天国", "highlight_label": "COVER", "highlight_text": "Originally by ALI PROJECT 「小女神花铃」OP", "mc_file": ""}, {"num": "M05", "title": "Determination Symphony", "highlight_label": "COVER", "highlight_text": "Originally by Roselia", "mc_file": ""}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "マヨイコンダモリ -探索-“迷失于深林”", "mc_file": ""}, {"num": "M06", "title": "Choir 'S' Choir", "highlight_label": "Live debut", "highlight_text": "", "mc_file": ""}, {"num": "M07", "title": "堕天", "highlight_label": "COVER", "highlight_text": "Originally by Creepy Nuts「彻夜之歌」OP", "mc_file": ""}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "コタエヲサガシテ -摩擦-“寻找答案”", "mc_file": ""}, {"num": "M08", "title": "神さま、バカ", "highlight_label": "Live debut", "highlight_text": "", "mc_file": ""}, {"num": "M09", "title": "PASSIONATE ANTHEM", "highlight_label": "COVER", "highlight_text": "Originally by Roselia", "mc_file": ""}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "キオクトゲンソウ -過去-“记忆与幻想”", "mc_file": ""}, {"num": "M10", "title": "Mas?uerade Rhapsody Re?uest", "highlight_label": "Live debut", "highlight_text": "", "mc_file": ""}, {"num": "", "title": "Interlude", "highlight_label": "Story Movie", "highlight_text": "カクセイヘノウタ -招待-“通往觉醒之歌”", "mc_file": ""}, {"num": "M11", "title": "Ave Mujica", "highlight_label": "Unreleased Song", "highlight_text": "", "mc_file": ""}],
    backstage: [{"photo": "../images/0thlive返图1.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图2.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图3.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图4.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图5.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图6.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图7.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图8.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}, {"photo": "../images/0thlive返图9.webp", "credit": "@bang_dream_info", "credit_text": "官方LIVE返图", "source_url": "https://x.com/i/status/1665312605727256576", "source_label": "View on X", "group_id": "0th LIVE 官推"}]
  }
];
