// 访谈数据
// 由 generate_all.py 自动生成，请勿手动修改

var interviewData = [
  {
    poster: "../images/弄和藤都子2.webp",
    date: "2026-03-31 00:00:00",
    interviewee: "藤都子 x 高尾奏音",
    title: "梦限大对谈采访连载「ゆめみたの WA ！」 第2回",
    if_translated: "yes",
    hash_id: "eoCADeAXqYd",
    sections: [{"id": "section-01", "title": "从第一印象中逐渐显现出的，两人的“真实一面”"}, {"id": "section-02", "title": "TV动画化确定时，两人各自的觉悟"}, {"id": "section-03", "title": "从3岁开始的“宿命”，与从16岁开始的挑战——各自的人生轨迹"}, {"id": "section-04", "title": "“你觉得音乐是快乐的吗？”"}, {"id": "section-05", "title": "没能以“很开心”来收尾"}, {"id": "section-06", "title": "想要一起去寻找那份闪耀"}],
    related: [{"id": "hHvY1EWykhY", "reason": "同系列"}, {"id": "EGHiOMHcXyX", "reason": "共同受访者：高尾奏音"}, {"id": "m58tZySEck6", "reason": "共同受访者：高尾奏音"}],
    previous_id: "hloIGz0UBX8",
    next_id: "hHvY1EWykhY",
    article_path: "articles/eoCADeAXqYd.js"
  },
  {
    poster: "../images/galleryless/dgm元素头图.webp",
    date: "2024-10-02 00:00:00",
    interviewee: "Diggy-MO'",
    title: "Ave Mujica Sound Producer Diggy-MO'访谈 & Elements概念解析",
    if_translated: "yes",
    hash_id: "1UhshAZcpdF",
    sections: [{"id": "section-01", "title": "母题为五大元素"}, {"id": "section-02", "title": "感觉变成了一个完整的故事"}, {"id": "section-03", "title": "决定接受邀请的关键因素是“她”的歌声"}, {"id": "section-04", "title": "01. Symbol I : △"}, {"id": "section-05", "title": "02. Symbol II : Air"}, {"id": "section-06", "title": "03. Symbol III : ▽"}, {"id": "section-07", "title": "04. Symbol IV : Earth"}, {"id": "section-08", "title": "05. Ether"}],
    related: [{"id": "vg0aUAR0CnH", "reason": "共同受访者：Diggy-MO'"}],
    previous_id: "jqNjeOrIDQb",
    next_id: "NDm8tZaWJgu",
    article_path: "articles/1UhshAZcpdF.js"
  },
  {
    poster: "../images/李子和阿拉蕾6.webp",
    date: "2026-06-16 00:00:00",
    interviewee: "仲町阿拉蕾 x 佐佐木李子",
    title: "梦限大对谈采访连载「ゆめみたの WA ！」 第5回",
    if_translated: "yes",
    hash_id: "hHvY1EWykhY",
    sections: [{"id": "section-01", "title": "正因同为主唱，才会彼此相互吸引"}, {"id": "section-02", "title": "主唱所认为的“好的歌唱”是什么？"}, {"id": "section-03", "title": "同为站在最前方之人的独特感受"}, {"id": "section-04", "title": "想要不断跃入梦限大的世界中"}],
    related: [{"id": "eoCADeAXqYd", "reason": "同系列"}, {"id": "m58tZySEck6", "reason": "共同受访者：佐佐木李子"}, {"id": "n7j1fu7Aamc", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "eoCADeAXqYd",
    next_id: "",
    article_path: "articles/hHvY1EWykhY.js"
  },
  {
    poster: "../images/240424李子单人访谈01.webp",
    date: "2024-04-24 00:00:00",
    interviewee: "佐佐木李子",
    title: "Ave Mujica、以“不自我设限”的姿态，引领前往“未曾有过的世界”",
    if_translated: "yes",
    hash_id: "ZiWd1iURLsj",
    sections: [{"id": "section-01", "title": "用新的手法和工具创造出的前所未有的表现"}, {"id": "section-02", "title": "如实地描绘出乐队姿态的新曲们"}, {"id": "section-03", "title": "通过录音发掘出作为主唱的可能性"}, {"id": "section-04", "title": "「“去创造只有Ave Mujica才能呈现的演唱会……”」 超越极限突飞猛进的未来"}],
    related: [{"id": "n7j1fu7Aamc", "reason": "共同受访者：佐佐木李子"}, {"id": "m58tZySEck6", "reason": "共同受访者：佐佐木李子"}, {"id": "VXjlXSdRiCl", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "m58tZySEck6",
    next_id: "B0F4USdjUL8",
    article_path: "articles/ZiWd1iURLsj.js"
  },
  {
    poster: "../images/20241002李子单人访谈01.webp",
    date: "2024-10-02 00:00:00",
    interviewee: "佐佐木李子",
    title: "诞生自「BanG Dream!」的异色重金属乐队 Ave Mujica所绽放的“黑暗之光”",
    if_translated: "yes",
    hash_id: "NDm8tZaWJgu",
    sections: [{"id": "section-01", "title": "只有在黑暗中才能闪耀的东西一定是存在着的"}, {"id": "section-02", "title": "越是了解就越感觉谜团重重的Doloris"}, {"id": "section-03", "title": "仿佛深深潜入歌词之海般的感觉"}, {"id": "section-04", "title": "Ave Mujica能成为任何存在"}],
    related: [{"id": "m58tZySEck6", "reason": "共同受访者：佐佐木李子"}, {"id": "ZiWd1iURLsj", "reason": "共同受访者：佐佐木李子"}, {"id": "DhvrDXRrWlS", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "1UhshAZcpdF",
    next_id: "0ZQv1f6v1zW",
    article_path: "articles/NDm8tZaWJgu.js"
  },
  {
    poster: "../images/galleryless/20250328羊李访谈.webp",
    date: "2025-03-28 00:00:00",
    interviewee: "Diggy-MO'",
    title: "Ave Mujica Sound Producer Diggy-MO' Completeness解说",
    if_translated: "yes",
    hash_id: "vg0aUAR0CnH",
    sections: [{"id": "section-01", "title": "「KiLLKiSS」"}, {"id": "section-02", "title": "「Georgette Me, Georgette You」"}, {"id": "section-03", "title": "「Imprisoned XII」"}, {"id": "section-04", "title": "「Crucifix X」"}, {"id": "section-05", "title": "「八芒星ダンス」"}, {"id": "section-06", "title": "「顔」"}, {"id": "section-07", "title": "「天球(そら)のMúsica」"}, {"id": "section-08", "title": "结语"}],
    related: [{"id": "1UhshAZcpdF", "reason": "共同受访者：Diggy-MO'"}],
    previous_id: "HfJYreVxg8X",
    next_id: "D8V8YJOLbPX",
    article_path: "articles/vg0aUAR0CnH.js"
  },
  {
    poster: "../images/230915全员访谈前篇01.webp",
    date: "2023-09-15 00:00:00",
    interviewee: "Ave Mujica",
    title: "Ave Mujica 0th Live后第1次全员访谈（前篇）",
    if_translated: "yes",
    hash_id: "KK084vBvyBK",
    sections: [{"id": "section-01", "title": "讲述五人五色的音乐与乐器历程"}, {"id": "section-02", "title": "作为乐手来分析Ave Mujica的魅力"}],
    related: [{"id": "bFRYIyvBbTN", "reason": "同系列"}, {"id": "MX8CI0pi7ii", "reason": "同为全员访谈"}, {"id": "wlMKzDwspiJ", "reason": "同为全员访谈"}],
    previous_id: "",
    next_id: "bFRYIyvBbTN",
    article_path: "articles/KK084vBvyBK.js"
  },
  {
    poster: "../images/230915全员访谈前篇15.webp",
    date: "2023-09-15 00:00:00",
    interviewee: "Ave Mujica",
    title: "Ave Mujica 0th Live后第1次全员访谈（后篇）",
    if_translated: "yes",
    hash_id: "bFRYIyvBbTN",
    sections: [{"id": "section-01", "title": "首张CD作品中展现出的非同寻常的音乐风貌"}, {"id": "section-02", "title": "以真人乐队与角色双重身份迈向的“下一个舞台”"}],
    related: [{"id": "KK084vBvyBK", "reason": "同系列"}, {"id": "MX8CI0pi7ii", "reason": "同为全员访谈"}, {"id": "wlMKzDwspiJ", "reason": "同为全员访谈"}],
    previous_id: "KK084vBvyBK",
    next_id: "MX8CI0pi7ii",
    article_path: "articles/bFRYIyvBbTN.js"
  },
  {
    poster: "../images/202404弄李访谈前篇01.webp",
    date: "2024-04-01 00:00:00",
    interviewee: "佐佐木李子 x 高尾奏音",
    title: "2024年4月 Animate 佐佐木李子 x 高尾奏音访谈（前篇）",
    if_translated: "yes",
    hash_id: "VXjlXSdRiCl",
    sections: [{"id": "section-01", "title": "“没想到竟然会说出‘混账老爹’这种台词”"}, {"id": "section-02", "title": "佐佐木小姐每天都会更新的那本笔记"}, {"id": "section-03", "title": "角色设定虽然黑暗，但角色之下的我们却很温暖。"}],
    related: [{"id": "m58tZySEck6", "reason": "同系列"}, {"id": "n7j1fu7Aamc", "reason": "同系列"}, {"id": "D8V8YJOLbPX", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "MX8CI0pi7ii",
    next_id: "n7j1fu7Aamc",
    article_path: "articles/VXjlXSdRiCl.js"
  },
  {
    poster: "../images/202404弄李访谈中篇01.webp",
    date: "2024-04-04 00:00:00",
    interviewee: "佐佐木李子 x 高尾奏音",
    title: "2024年4月 Animate 佐佐木李子 x 高尾奏音访谈（中篇）",
    if_translated: "yes",
    hash_id: "n7j1fu7Aamc",
    sections: [{"id": "section-01", "title": "不仅在声音上，也想通过动作与彼此相连"}, {"id": "section-02", "title": "独一无二的世界观，无限可能的乐队"}, {"id": "section-03", "title": "走过 0th LIVE，终于迈向 1st LIVE"}],
    related: [{"id": "m58tZySEck6", "reason": "同系列"}, {"id": "VXjlXSdRiCl", "reason": "同系列"}, {"id": "D8V8YJOLbPX", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "VXjlXSdRiCl",
    next_id: "m58tZySEck6",
    article_path: "articles/n7j1fu7Aamc.js"
  },
  {
    poster: "../images/202404弄李访谈后篇01.webp",
    date: "2024-04-07 00:00:00",
    interviewee: "佐佐木李子 x 高尾奏音",
    title: "2024年4月 Animate 佐佐木李子 x 高尾奏音访谈（后篇）",
    if_translated: "yes",
    hash_id: "m58tZySEck6",
    sections: [{"id": "section-01", "title": "“我一边感受着大家，一边歌唱”"}, {"id": "section-02", "title": "疯狂的Riff Master所演奏的紧张琶音"}, {"id": "section-03", "title": "「美好的世界，但是并不存在」"}, {"id": "section-04", "title": "在『BanG Dream! Ave Mujica』中“得到了救赎”"}, {"id": "section-05", "title": "迈向美好的未来"}],
    related: [{"id": "n7j1fu7Aamc", "reason": "同系列"}, {"id": "VXjlXSdRiCl", "reason": "同系列"}, {"id": "D8V8YJOLbPX", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "n7j1fu7Aamc",
    next_id: "ZiWd1iURLsj",
    article_path: "articles/m58tZySEck6.js"
  },
  {
    poster: "../images/202404atm访谈01.webp",
    date: "2024-04-25 00:00:00",
    interviewee: "渡濑结月 x 冈田梦以 x 米泽茜",
    title: "2024年4月 Lisani 渡濑结月 x 冈田梦以 x 米泽茜访谈",
    if_translated: "no",
    hash_id: "B0F4USdjUL8",
    sections: [{"id": "section-01", "title": "Ave Mujica 给世界带来的冲击，以及粉丝的反应与回响"}, {"id": "section-02", "title": "“破坏”与“创造”——象征乐队故事与多面性的新曲们"}, {"id": "section-03", "title": "以角色身份进行舞台表现时，各自所注重的方面"}, {"id": "section-04", "title": "1st LIVE、配信单曲，永不停息燃烧着的 Ave Mujica 之火"}, {"id": "section-05", "title": "在乐队活动中各自找到的挑战与成就感"}, {"id": "section-06", "title": "终有一天走向世界！2nd LIVE，以及通往更远未来的 Ave Mujica 野心"}],
    related: [{"id": "EGHiOMHcXyX", "reason": "共同受访者：渡濑结月"}, {"id": "n7j1fu7Aamc", "reason": "相近主题"}, {"id": "m58tZySEck6", "reason": "相近主题"}],
    previous_id: "ZiWd1iURLsj",
    next_id: "jqNjeOrIDQb",
    article_path: "articles/B0F4USdjUL8.js"
  },
  {
    poster: "../images/voicefebrivol116.webp",
    date: "2025-01-13 00:00:00",
    interviewee: "Ave Mujica",
    title: "Voice Febri Vol.1 杂志全员访谈",
    if_translated: "no",
    hash_id: "wlMKzDwspiJ",
    sections: [],
    related: [{"id": "HfJYreVxg8X", "reason": "同为全员访谈"}, {"id": "hloIGz0UBX8", "reason": "同为全员访谈"}, {"id": "KK084vBvyBK", "reason": "同为全员访谈"}],
    previous_id: "0ZQv1f6v1zW",
    next_id: "EGHiOMHcXyX",
    article_path: "articles/wlMKzDwspiJ.js"
  },
  {
    poster: "../images/galleryless/月刊bushiroad202402访谈cover.webp",
    date: "2024-01-06 00:00:00",
    interviewee: "Ave Mujica",
    title: "月刊ブシロード2024年2月号 杂志全员访谈",
    if_translated: "yes",
    hash_id: "MX8CI0pi7ii",
    sections: [],
    related: [{"id": "HfJYreVxg8X", "reason": "同为全员访谈"}, {"id": "KK084vBvyBK", "reason": "同为全员访谈"}, {"id": "bFRYIyvBbTN", "reason": "同为全员访谈"}],
    previous_id: "bFRYIyvBbTN",
    next_id: "VXjlXSdRiCl",
    article_path: "articles/MX8CI0pi7ii.js"
  },
  {
    poster: "../images/横k鸡狗1场刊02.webp",
    date: "2025-04-26 00:00:00",
    interviewee: "Ave Mujica",
    title: "「わかれ道の、その先へ」 CONCEPT PHOTOBOOK访谈 Ave Mujica部分",
    if_translated: "no",
    hash_id: "hloIGz0UBX8",
    sections: [],
    related: [{"id": "wlMKzDwspiJ", "reason": "同为全员访谈"}, {"id": "HfJYreVxg8X", "reason": "同为全员访谈"}, {"id": "0ZQv1f6v1zW", "reason": "同为全员访谈"}],
    previous_id: "DhvrDXRrWlS",
    next_id: "eoCADeAXqYd",
    article_path: "articles/hloIGz0UBX8.js"
  },
  {
    poster: "../images/lisani2025_am10.webp",
    date: "2025-01-25 00:00:00",
    interviewee: "Ave Mujica",
    title: "リスアニ!LIVE 2025 场刊 Ave Mujica部分",
    if_translated: "yes",
    hash_id: "HfJYreVxg8X",
    sections: [],
    related: [{"id": "MX8CI0pi7ii", "reason": "同为全员访谈"}, {"id": "wlMKzDwspiJ", "reason": "同为全员访谈"}, {"id": "hloIGz0UBX8", "reason": "同为全员访谈"}],
    previous_id: "EGHiOMHcXyX",
    next_id: "vg0aUAR0CnH",
    article_path: "articles/HfJYreVxg8X.js"
  },
  {
    poster: "../images/202408113p对谈01.webp",
    date: "2024-08-11 00:00:00",
    interviewee: "斋藤光二 x 绪方航贵 x 松本拓辉",
    title: "『Anisama 2024』斋藤P x “MyGO!!!!!”P 绪方航贵 x “Ave Mujica”P 松本拓辉 三方对谈",
    if_translated: "no",
    hash_id: "jqNjeOrIDQb",
    sections: [{"id": "section-01", "title": "与Bushiroad企划的勾结是“没有的事！”"}, {"id": "section-02", "title": "MyGO!!!!!那些难读标题的诞生秘闻"}, {"id": "section-03", "title": "制作人亲自指导Ave Mujica甩头"}, {"id": "section-04", "title": "谈论女子乐队企划蓬勃发展的当下"}, {"id": "section-05", "title": "何为“Anisama中的胜负”？"}, {"id": "section-06", "title": "以“把一切统统砸烂”的心态去挑战"}],
    related: [{"id": "DhvrDXRrWlS", "reason": "共同受访者：松本拓辉"}],
    previous_id: "B0F4USdjUL8",
    next_id: "1UhshAZcpdF",
    article_path: "articles/jqNjeOrIDQb.js"
  },
  {
    poster: "../images/20241211lisani全员访谈01.webp",
    date: "2024-12-11 00:00:00",
    interviewee: "Ave Mujica",
    title: "「リスパレ！チョイス」选出艺人・Ave Mujica 访谈",
    if_translated: "yes",
    hash_id: "0ZQv1f6v1zW",
    sections: [{"id": "section-01", "title": "成员回顾作为乐队开启新篇章的3rd LIVE！"}, {"id": "section-02", "title": "作为乐队一路加深羁绊的回忆，以及各自钟爱的那些歌曲"}, {"id": "section-03", "title": "如果Ave Mujica开始做广播节目的话……？"}, {"id": "section-04", "title": "对即将到来的 Ave Mujica 之年的抱负与决心"}],
    related: [{"id": "HfJYreVxg8X", "reason": "同为全员访谈"}, {"id": "wlMKzDwspiJ", "reason": "同为全员访谈"}, {"id": "KK084vBvyBK", "reason": "同为全员访谈"}],
    previous_id: "NDm8tZaWJgu",
    next_id: "wlMKzDwspiJ",
    article_path: "articles/0ZQv1f6v1zW.js"
  },
  {
    poster: "../images/20241211lisani全员访谈01.webp",
    date: "2025-01-17 00:00:00",
    interviewee: "渡濑结月 x 高尾奏音",
    title: "「リスパレ！チョイス」选出艺人・Ave Mujica x 丰田穗乃花 对谈",
    if_translated: "no",
    hash_id: "EGHiOMHcXyX",
    sections: [{"id": "section-01", "title": "「リスパレ！」力荐 Ave Mujica 的理由是什么？"}, {"id": "section-02", "title": "回顾那场伴随震撼惊喜一同呈现的4th LIVE"}, {"id": "section-03", "title": "聊聊热门OP「KiLLKiSS」与动画配音的幕后故事！"}, {"id": "section-04", "title": "也请留意歌词！让人直到最后都沉浸于动画世界的ED"}, {"id": "section-05", "title": "假如Ave Mujica要推出自己的专属广播节目的话……？"}],
    related: [{"id": "n7j1fu7Aamc", "reason": "共同受访者：高尾奏音"}, {"id": "B0F4USdjUL8", "reason": "共同受访者：渡濑结月"}, {"id": "m58tZySEck6", "reason": "共同受访者：高尾奏音"}],
    previous_id: "wlMKzDwspiJ",
    next_id: "HfJYreVxg8X",
    article_path: "articles/EGHiOMHcXyX.js"
  },
  {
    poster: "../images/20250328羊李对谈01.webp",
    date: "2025-03-28 00:00:00",
    interviewee: "羊宫妃那 x 佐佐木李子",
    title: "natalie 羊宫妃那 x 佐佐木李子对谈 历经跌宕起伏的故事后，如今两人心中所想",
    if_translated: "no",
    hash_id: "D8V8YJOLbPX",
    sections: [{"id": "section-01", "title": "有笑声的「It's MyGO!!!!!」现场，与气氛沉重的「Ave Mujica」现场"}, {"id": "section-02", "title": "「人間になりたいうたII」「春日影」的演唱中所倾注的讲究"}, {"id": "section-03", "title": "散布点缀在「Ave Mujica」中身为初音的心境"}, {"id": "section-04", "title": "彼此对对方乐队的印象是“好厉害！”“蒸蒸日上”"}, {"id": "section-05", "title": "“真的很多” 「BanG Dream!」主唱的辛苦之处"}, {"id": "section-06", "title": "希望办成一场让人感叹“也曾有过这样的事啊”、并能勾起故事回忆的合同Live"}],
    related: [{"id": "DhvrDXRrWlS", "reason": "共同受访者：佐佐木李子"}, {"id": "n7j1fu7Aamc", "reason": "共同受访者：佐佐木李子"}, {"id": "m58tZySEck6", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "vg0aUAR0CnH",
    next_id: "DhvrDXRrWlS",
    article_path: "articles/D8V8YJOLbPX.js"
  },
  {
    poster: "../images/20250328李子松本p对谈01.webp",
    date: "2025-03-28 00:00:00",
    interviewee: "佐佐木李子 x 松本拓辉",
    title: "Real Sound 佐佐木李子×松本拓辉P揭秘Ave Mujica幕后 “丝毫不妥协这一点让人欣喜”",
    if_translated: "no",
    hash_id: "DhvrDXRrWlS",
    sections: [{"id": "section-01", "title": "朗读剧中埋下的TV动画『Ave Mujica』的伏笔"}, {"id": "section-02", "title": "正因为是“能直言不讳交换意见”的团队，才孕育出 Ave Mujica 的现场演出"}, {"id": "section-03", "title": "「KiLLKiSS」中所倾注的 Diggy-MO’ 的执着"}, {"id": "section-04", "title": "迷你专辑『ELEMENTS』诞生秘话"}, {"id": "section-05", "title": "谈谈TV动画『BanG Dream! Ave Mujica』第10话以后的乐曲"}, {"id": "section-06", "title": "分歧路口，前途漫漫"}, {"id": "section-07", "title": "佐佐木李子 × 松本拓辉眼中的Ave Mujica未来"}],
    related: [{"id": "D8V8YJOLbPX", "reason": "共同受访者：佐佐木李子"}, {"id": "VXjlXSdRiCl", "reason": "共同受访者：佐佐木李子"}, {"id": "m58tZySEck6", "reason": "共同受访者：佐佐木李子"}],
    previous_id: "D8V8YJOLbPX",
    next_id: "hloIGz0UBX8",
    article_path: "articles/DhvrDXRrWlS.js"
  }
];
