// 曲目数据
// 由 generate_all.py 自动生成，请勿手动修改

const songsData = [
  {
    name: "Georgette Me, Georgette You",
    name_jp: "Georgette Me, Georgette You",
    album: "Digital Single",
    album_year: "2025",
    release_date: "2025/1/15",
    cover: "../images/GMGY.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "松坂康司（SUPA LOVE）",
    arranger: "松坂康司（SUPA LOVE）",
    first_stage: "リスアニ!LIVE 2025 SATURDAY STAGE",
    mv_url: "https://www.bilibili.com/bangumi/play/ep1365126",
    lyrics_jp: "白銀の糸を伝い 想い 手繰り寄せてた\\nその果てで妊る月 抱きしめたなら\\n待っているの 太陽から夜が堕ちてくるのを\\nねぇ その果てで満たしてよ 届く気がするの\\nもつれたまま 踊る Georgette Me, Georgette You まわる\\n痛むほどに ほら 煌めくドレスを纏いながら\\neverlastin’ ever.. darlin’ ever, ever.. 締め付けて again\\neverlastin’ ever.. 離れぬように ever, ever, ever..\\n縛るものはなに？ それは 誰かの遠い祈り\\nああ 最初から知っていたわ 許されないこと\\n愛せぬまま 踊る Georgette Me, Georgette You is that true?\\nあなたが触れたわ この傷口に\\nもつれたまま 踊る Georgette Me, Georgette You まわる\\nこのまま このままでいさせて\\n愛せぬまま 踊る Georgette Me, Georgette You is that true?\\n痛みは光ね 煌めくドレスを纏いながら\\neverlastin’ ever.. darlin’ ever, ever.. 締め付けて again\\neverlastin’ ever.. 離れぬように ever, ever, ever..\\n",
    lyrics_cn: "沿着白银的丝线 将思念牵至身边\\n在那尽头所孕育的月 若能将它拥入怀中\\n等待着 夜晚从太阳坠落\\n啊 在那尽头将我满足 思绪仿佛能够传达\\n缠绵不清 翩翩起舞 Georgette Me, Georgette You 旋转不停\\n越是痛苦不已 看啊 身缠礼服愈加闪耀\\n直到永远…亲爱的 永远永远…再次将你我紧缚\\n直到永远…为了永不分离 永远 永远 永远…\\n束缚我们的是什么？是某人遥远的祈祷\\n啊啊 最初我便知晓 这是不被允许之事\\n无法相爱 翩翩起舞 Georgette Me, Georgette You 这是否真实？\\n是你触碰到了啊 这处伤口\\n缠绵不清 翩翩起舞 Georgette Me, Georgette You 旋转不停\\n就这样 就让我们一直这样下去\\n无法相爱 翩翩起舞 Georgette Me, Georgette You 这便是真实？\\n痛苦是光明呢 看啊 身缠礼服闪耀至此\\n直到永远…亲爱的 永远 永远…再次将你我紧缚\\n直到永远…为了永不分离 永远 永远 永远…",
    appearances: ["KiLLKiSS", "Completeness", "Ave Música"],
    comments: [
      { text: "我希望能够用“白银的乔其纱（Georgette）”作为比喻，来表达那经过戏剧化处理的情感故事——因此我这样写下了这首歌。此外，我也希望能利用那反复出现的“月”这一意象，在每首歌曲中唤起不同的想象力。在这首歌中，我尤其像绘制美丽画作般，用心地逐字逐句编织了每一个词句。“拒绝”“接受”人们在这场名为“人生”的大舞台上，不停地扮演着自己；有时，甚至会活成另一个完全不同的人。我也希望能表达出这样一种意味：我们都在某处明白，存在着一种无法掌控却注定被引导的命运。令人惊异的是，人总是能同时兼容那些看似矛盾的特质。关键在于那种“微妙”的存在，也在于其“脆弱得令人畏惧”。作为一贯的风格，我在第二段还加入了一些隐约让人联想到宗教背景的短语。转折点的到来——可以认为，在人生的每一个意义上，总是在“失去”之后，才会迎来真正的新起点。“你触碰了这道伤口”（「あなたが触れたわ　この傷口に」）如果我们将其理解为在逐渐领悟人生的过程中，那层层叠叠闪耀的光芒，既象征着痛苦，也正因黑暗越深而愈发璀璨。这是一首始终专注于“文字描绘”的歌曲。此外，这首歌在确立一种与动画截然不同的“独立性”的过程中，还兼具表达出人们拼尽全力延续生命的美丽，以及可被解读为恋爱关系表达的层面。", source: "https://natalie.mu/music/pp/avemujica03/page/3", from: "Diggy-MO'" }
    ],
    live_history: [
      { date: "2025/1/25", venue: "日本武道館", name: "リスアニ!LIVE 2025 SATURDAY STAGE", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476" },
      { date: "2025/2/2", venue: "KT Zepp Yokohama", name: "Ave Mujica「KiLLKiSS」購入者限定フリーライブ", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_2" },
      { date: "2025/4/26", venue: "Kアリーナ横浜", name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」DAY1 : Petrichor", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_3" },
      { date: "2025/4/27", venue: "Kアリーナ横浜", name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」DAY2 : Geosmin", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_4" },
      { date: "2025/5/5", venue: "千葉市蘇我スポーツ公園", name: "rockin'on presents JAPAN JAM 2025", has_video: false, video_url: "" },
      { date: "2025/6/7", venue: "Smart Araneta Coliseum", name: "ANISAMA WORLD 2025 in MANILA", has_video: false, video_url: "" },
      { date: "2025/10/11", venue: "梅赛德斯-奔驰文化中心 （Mercedes-Benz Arena）", name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」上海追加公演 DAY1 : Petrichor", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_5" },
      { date: "2025/10/12", venue: "梅赛德斯-奔驰文化中心 （Mercedes-Benz Arena）", name: "MyGO!!!!!×Ave Mujica 合同ライブ「わかれ道の、その先へ」上海追加公演 DAY2 : Geosmin", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_6" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac47924476_7" },
      { date: "2026/8/9", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY2", has_video: false, video_url: "" },
      { date: "2026/8/16", venue: "幕張メッセ", name: "SUMMER SONIC 2026 TOKYO", has_video: true, video_url: "" }
    ]
  },
  {
    name: "Symbol III : Water",
    name_jp: "Symbol III : 🜄",
    album: "Digital Single",
    album_year: "2024",
    release_date: "2024/6/15",
    cover: "../images/water.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "トミタカズキ(SUPA LOVE) • Diggy-MO'",
    arranger: "トミタカズキ(SUPA LOVE)",
    first_stage: "Ave Mujica 2nd LIVE「Quaerere Lumina」 爱知公演",
    mv_url: "https://www.bilibili.com/video/BV17w4m1Y7kf/",
    lyrics_jp: "月を詠む 海のリズム\\n私は ‘最初に降り立った者’\\n流れ出す このプログラム\\n引き合う魂 魂の歌が\\n叫ぶの 欲望を 命の緊張を高めてゆくわ\\n寄せる 寄せる 寄せる波 私の性の中で\\n馳せる 馳せる 馳せる夢 微かな音を抱きしめて\\n揺れる 揺れる 揺れる愛 あなた対極にいて その炎と重なって\\nいま ‘大宇宙(おおぞら)’になる\\n可哀想に おいでなさい\\nついには影を手放したのね\\n古い本は焼き払われ\\n時代が通り過ぎてゆく\\nいまでも 幸せなその’死’の訪れをただ祈りながら\\n寄せる 寄せる 寄せる波 すべてを 嗚呼 受け入れて\\n馳せる 馳せる 馳せる夢 何もかもを失って\\n揺れる 揺れる 揺れる愛 遠く近く あなたの炎が舞い上がる\\n世界は白くなる\\n導くように\\n小さな磁気を帯びて煌めいている場所がある\\nそう 私はかつて最初に降り立った者\\nこの白き世界に\\n寄せる 寄せる 寄せる波 ‘生’の中で\\n馳せる 馳せる 馳せる夢 微かな音を抱きしめて\\n揺れる 揺れる 揺れる愛 ああ その命(ほのお)と重なって\\nいま ‘大空’になる",
    lyrics_cn: "吟咏月色 海之节奏\\n我是“最初降临之人”\\n既定的程式运作流转\\n彼此吸引的灵魂 灵魂之歌\\n呐喊的欲望 绷紧生命的琴弦\\n翻涌 翻涌 波浪层层涌来 在我的天性中激荡\\n疾驰 疾驰 梦想奔向远方 怀抱微弱的余音\\n摇曳 摇曳 爱情动摇不定 与身处对极的你 同那火焰重叠在一起\\n此刻 化作广阔天空\\n真是可怜 过来吧\\n终于舍弃了影子呢\\n旧书被焚毁\\n一个时代渐渐远去\\n直到如今 仍只祈祷着幸福的死亡降临\\n翻涌 翻涌 波浪层层涌来 啊啊 将所有尽数接纳\\n疾驰 疾驰 梦想奔向远方 纵然失去一切\\n摇曳 摇曳 爱情动摇不定 似近似远 你的火焰飞扬而起\\n世界变得一片纯白\\n仿佛命运指引一般\\n有处地方带微弱的磁场 闪烁光芒\\n没错 我是最初降临于此之人\\n在这纯白的世界\\n翻涌 翻涌 波浪层层涌来 在生命之中\\n疾驰 疾驰 梦想奔向远方 怀抱微弱的回响\\n摇曳 摇曳 爱情动摇不定 啊啊 与生命之火交融\\n此刻 化作无垠宇宙",
    appearances: ["ELEMENTS"],
    comments: [
      { text: "我在副歌的乐句中加入了“波浪”这一意象，它也是司掌水的精灵“温蒂妮”的语源。将“月亮”与“地球”相对比，以超然达观的视角进行了唯美的刻画，同时，也是因为我想要描绘出一个具有官能美的世界观。我刻意引入了处于对立面的阳性特质“火”，以此来反衬阴性特质“水”的神秘，使其更为深邃、宏大。内容上，最初我构建了一个从“月之使者降临此大地”开始的故事。我将这个“月之使者”设定成了，比如高维度的存在，掌管着阴性宫位～，诸如此类的感觉。对于高次元的存在而言，人类的历史不过是转瞬即逝的一瞬。于是，她俯视着这个地上——即三维的“Human Race”（人类种族），并将自己曾经历过的那些故事，如同追溯种种回忆一般，由她本人作为“讲述者”亲自道来，我是这样设定的。此外，歌词中也包含了很多跨越时代前后的复合元素，例如我运用了克里姆特“爱欲与死亡共存”这种偏近代的艺术概念，或者也融入了塔罗牌牌组所展现的那种联想空间。通过探索这些不同主题的组合，或许能进一步升华为Ave Mujica式的格调，那便是我的期望。我特意放入“欲望”、“紧张”、或者是“大宇宙”这样直白露骨的词汇，也是出于这一目的。阴性特质将阳性特质包容进去，形成一种宏大的感觉。在表达“两性交融”这一直接含义的同时，另一方面，我也将宗教的根源作为多层面的概念融入其中。阳性宫位之火的“△”与阴性宫位之水的“▽”重合，就会变成“六芒星”的符号，而这正意味着“大宇宙”，因此在第一段副歌中，我试图表达这种宇宙的完满性因果与秩序。而在最后的部分，我的期望是，最终不去描绘那种“大宇宙”般不可估量的宏大事物，而是珍重地描绘活在此刻“生命”中的“最微小的世界”。为了让听众能感受到这一点，我在结尾处忽然将视角拉回，只是从地上仰望这片“天空”。于是，支线故事包含着“生命赞歌”的含义，而我这首歌想要表达的本质依旧是“爱之歌”。", source: "https://natalie.mu/music/pp/avemujica02/page/2", from: "Diggy-MO'" }
    ],
    live_history: [
      { date: "2024/7/7", venue: "愛知県芸術劇場 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」爱知公演", has_video: false, video_url: "" },
      { date: "2024/10/13", venue: "河口湖ステラシアター", name: "Ave Mujica 3rd LIVE「Veritas」", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965" },
      { date: "2024/12/14", venue: "武蔵野の森総合スポーツプラザ", name: "Roselia「Stille Nacht, Rosen Nacht」", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_2" },
      { date: "2024/12/15", venue: "武蔵野の森総合スポーツプラザ", name: "Ave Mujica 4th LIVE「Adventus」", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_3" },
      { date: "2025/2/2", venue: "KT Zepp Yokohama", name: "Ave Mujica「KiLLKiSS」購入者限定フリーライブ", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_4" },
      { date: "2025/7/26", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_5" },
      { date: "2025/7/27", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_6" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac47930965_7" },
      { date: "2026/8/8", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY1", has_video: false, video_url: "" }
    ]
  },
  {
    name: "Sophie",
    name_jp: "Sophie",
    album: "3rd Single 「'S/' The Way / Sophie」",
    album_year: "2025",
    release_date: "2025/12/10",
    cover: "../images/slash特装.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "Diggy-MO' • ÐIK",
    arranger: "Diggy-MO' • ÐIK",
    first_stage: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演",
    mv_url: "https://www.bilibili.com/video/BV1UR2DB6ErR",
    lyrics_jp: "太陽は山羊座へ向かう\\nいま 天（そら）は黒い海で 嗚呼 満たされて\\nそう わたしのこころ 悲鳴は神に届かぬと憂いて\\n運命（さだめ）嘆いて\\nまた カーテシーがあなたの欲情を掻き立てる\\n‘美徳’ とこの魂 何処へ\\n誘って 誘って 誘って 誘って 嘲笑って こんなわたしを辱めて\\nもうヤダって ヤダって 嫌だって だからやめて ほんとヤダ...\\n絶望のハイライト 揺れる死神の影\\nhow bizarre\\n腐敗したハイエロファント\\n至上の愉悦を覚え わたしから掠め取ってゆく\\n純潔は壊され\\nmaterial, material, material, how bizarre\\nmaterial, material,.. この ‘不幸’ を呪って\\n誘って 誘って 誘って 誘って 嘲笑って こんなわたしを辱めて\\nもうヤダって ヤダって 嫌だって だからやめて ほんとヤダ...\\nほんとヤダ... ほんとヤダ... ほんとヤダ...\\n儚い夢に取り憑かれているのかしら\\nそう この世で ‘美徳’ など 報いられないの\\n欺かれ続け 嗚咽と涙に 嗚呼 咽ぶばかりで\\n嫌だって... ほんとヤダ...\\nこんなことならいっそ...\\n絶望のハイライト 揺れる死神の影\\n",
    lyrics_cn: "太阳向摩羯座西沉\\n啊 此刻 天空被漆黑的海洋填满\\n是的 我的心 忧虑着悲鸣无法传达给神明\\n哀叹着命运\\n又一次 屈膝礼在挑起你的情欲\\n‘美德’和这灵魂 将去往何处\\n引诱我 引诱我 引诱我 引诱我 嘲笑我 羞辱这样的我\\n不想再这样下去 不想 不要 所以请不要 真的好讨厌…\\n绝望的高光高潮 摇曳的死神之影\\nhow bizarre\\n腐败的神启者\\n感受这至高的欢愉 从我身上掠夺而去\\n纯洁被破坏\\nmaterial, material, material, how bizarre\\nmaterial, material,..诅咒这份‘不幸’\\n引诱我 引诱我 引诱我 引诱我 嘲笑我 羞辱这样的我\\n不想再这样下去 不想 不要 所以请不要 真的好讨厌…\\n真的好讨厌… 真的好讨厌… 真的好讨厌…\\n莫非是被虚妄的梦附身了吗？\\n是的 在这个世上 ‘美德’之类是没有回报的\\n持续被欺骗 在呜咽和泪水之中 啊 唯有哽咽\\n不要…真的好讨厌…\\n既然如此 不如干脆…\\n绝望的高光高潮 摇曳的死神之影",
    appearances: ["'S/' The Way / Sophie"],
    comments: [
      { text: "——「Sophie」是基于怎样的概念开始制作的？\\n我想到了“唯物主义”这个概念，所以一边以萨德侯爵的《美德的不幸》为母题（Motif），一边将其投射到Ave Mujica的世界观中。我也引入了情色主义（Eroticism）的要素，截取了原本的人性得到释放、赤裸裸的残酷瞬间。另外，作为暗线主题，我还追溯时代，复合地融合了将诺斯替主义（Gnosticism）的宇宙观、神话及宗教背景等。\\n——具体是以怎样的意象进行拓展的呢？\\n我认为如果做一些诸如价值观或道德观念瓦解这种彻底崩塌的意象，能够引发出她们与以往不同的魅力。我将其比作现代社会的构图，在不损品格的前提下，引入处于极限边缘的表现形式并使其具象化。其实对我来说，这并不是什么罕见的切入点，但我认为，向一般的音乐受众展示这种表现形式的普遍性，也是一个重要的机会。我将猎奇、无神论等脑海中的意象进行各种组合，以此煽动那种生猛感。\\n——钢琴的音色非常优美，请问使用的是什么？如果是软件音源的话请告诉我们音色名称。\\n是NATIVE INSTRUMENTS Kontakt的Alicia's Keys。因为挂了几个效果器，所以可能听起来和原本的音色相去甚远。\\n——关于弦乐编曲，是从编制开始构建的吗？\\n这首歌的编制是以四重奏来组建的。不出所料这部分也是和人声主旋律以及其他乐器的合奏同步制作的。感觉就像是将脑海中听到的旋律和复调（Counter）乐句，在各自通道上用MIDI写成乐谱。因为这个乐队也有钢琴，所以需要一边弹钢琴一边将所有内容包含在内进行编曲。\\n——具体的作业是如何进行的呢？\\n基本上是先在四重奏的各个通道上制作相互交织的乐句。有时也会像常规手法那样，先在一个通道上把音源设为弦乐整体的组合，一边先决定大概的轮廓，也有这样的情况。在具体区分制作时，虽然令人印象深刻的乐句主要由第一小提琴担任的情况很多，但在一些细小的声部或段落中，当然也有很多情况会让大提琴或中提琴来承担这一角色。这方面我也在仔细斟酌合奏中交织乐句的机能美。我的目标是既能让主唱突显出来，又能留下“弦乐和钢琴很帅气的曲子”这一印象的、行之有效的精心制作。\\n——请教一下使用的音源和效果器。\\n音源选择了VIENNA SYMPHONIC LIBRARY。在通过编程还原弦乐时，我会仔细选择表情控制、音量写入以及演奏法，来打磨细腻的表现。在效果处理方面，通常管弦乐等的弦乐不会加太多压缩，但在流行乐的情况下，我会使用磁带系的效果器，在不破坏抑扬顿挫的程度内微量增加并进行处理。\\n——感觉面向结尾的高潮部分紧紧抓住了人心。你是如何考量并构建这种展开的呢？\\n无论创作什么歌曲，我都都会下功夫维持紧张感。我认为这也算是某种关于如何捕捉“意外性”的部分。在这首歌里，因为我认为特别是必须要将紧迫感一直煽动到最后，所以一边计算着主唱人声最终到达的表现境界，一边在最后的一个大段落里整个引入机关，构建出令人提心吊胆的结构。", source: "Sound ＆ Recording 2026.02", from: "Diggy-MO'" },
      { text: "──「Sophie」真的是一首只有佐佐木小姐才能驾驭的曲子……总而言之，我感到非常震惊。是一首极其厉害的歌。\\n佐佐木：我也从来没有唱过这样的歌。必须全身心投入，以至于在演唱过程中甚至像是失去了记忆，不彻底沉浸进去就唱不出来。当时已经完全进入了心流状态……该怎么形容呢，感觉脑细胞在被逐渐破坏，血管都快要爆裂了一样。根本无法用普通的方式去演唱。\\n\n──「Sophie」的歌词我最初拜读的时候也受到了极大的冲击，甚至有点不知道该如何去形容。\\n佐佐木：真的呢。这是一首只有 Ave Mujica 才能做到的曲子吧。能够被委以重任演唱这样的歌我感到很荣幸，而且乐器部分的编排也非常厉害。一般来说，这种曲子是不会突然让给别人唱的。所以，这也激发了我们“大干一场吧！”的斗志。我非常开心。\\n\n──刚拿到这首曲子的时候，您最直观的想法是什么？\\n佐佐木：首先我觉得“这根本不是在唱歌”。这是呐喊……灵魂的尖叫。但是，我想把这种“尖叫”一直贯彻到最后。毕竟这首曲子传达的就是这样的东西。我在参考Demo的同时，也想唱出自己心中描绘的「Sophie」，所以里面也有我完全改变了原本唱法的部分。比如第2段主歌之后的尖叫。我觉得这里应该可以自由发挥，所以就没有和大家商量直接尝试了一次，结果就被采用了。\\n\n──是〈material, material,〉那一段对吧。令人印象非常深刻。\\n佐佐木：那一段我听都想问“这到底是谁在唱啊”……我的记忆就是缺失到了那种程度。唱歌的时候，我好像在用力抓挠自己的身体，回家的路上觉得身上疼，一看才惊讶地发现满是抓痕。我当时就想，“原来被歌曲附身演唱就是这种感觉啊”（苦笑）。\\n\n──甚至连这个小插曲都跟这首曲子无比契合呢。我很迷茫，不知道应该怎么说才好，像是被袭击了，但又仿佛是被引诱了……\\n佐佐木：是啊。感觉像是在歌唱某种“完全没有道理可言之事”，但也可以理解为在“享受这种不公”。比如那句“真的好讨厌”（ほんとヤダ），到底是不是真的在抗拒呢。\\n\n──确实是这样。在不断重复〈真的好讨厌〉的过程中，语气和情感也发生了变化，这点也引人深思。\\n佐佐木：感觉就像是把那种真实的“动摇”原封不动地塞了进去。我觉得在最后选用的音轨里，也有制作团队刻意保留下来的粗糙、未经修饰的部分。我非常喜欢最后一段副歌里的高音，那里的狂野的爆发力非常棒，还有“引诱我”（誘って）那句稍微残留的换气声，也刻意按原样保留了下来。甚至连叹息声、呜咽声也都原封不动地保留了，希望大家在听的时候也能去享受这些细节。", source: "https://www.animatetimes.com/news/details.php?id=1765333295&p=3", from: "佐佐木李子" }
    ],
    live_history: [
      { date: "2025/12/14", venue: "東京国際フォーラム ホールA", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972" },
      { date: "2026/1/15", venue: "グランキューブ大阪 メインホール", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演", has_video: false, video_url: "" },
      { date: "2026/2/28", venue: "Kアリーナ横浜", name: "BanG Dream! 10th Anniversary LIVE「In the name of BanG Dream!」", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972_2" },
      { date: "2026/3/1", venue: "Kアリーナ横浜", name: "MyGO!!!!!×Ave Mujica ツーマンライブ「“moment / memory”」", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972_3" },
      { date: "2026/3/20", venue: "神戸ワールド記念ホール", name: "MEGA VEGAS 2026", has_video: false, video_url: "" },
      { date: "2026/4/4", venue: "KT Zepp Yokohama", name: "CENTRAL MUSIC & ENTERTAINMENT FESTIVAL 2026", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972_4" },
      { date: "2026/4/11", venue: "台北・大佳河濱公園", name: "BanG Dream! Special LIVE in TAIPEI DAY1 : MyGO!!!!!×Ave Mujica「\"moment / memory\"」", has_video: false, video_url: "" },
      { date: "2026/4/17", venue: "Zepp Fukuoka", name: "Ave Mujica LIVE TOUR 2026「Exitus」福冈公演", has_video: false, video_url: "" },
      { date: "2026/4/26", venue: "Zepp Namba", name: "Ave Mujica LIVE TOUR 2026「Exitus」大阪公演", has_video: false, video_url: "" },
      { date: "2026/5/1", venue: "Zepp Nagoya", name: "Ave Mujica LIVE TOUR 2026「Exitus」爱知公演", has_video: false, video_url: "" },
      { date: "2026/5/4", venue: "Zepp Haneda (TOKYO)", name: "Ave Mujica LIVE TOUR 2026「Exitus」东京公演", has_video: false, video_url: "" },
      { date: "2026/6/19", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972_5" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac48115972_6" },
      { date: "2026/8/8", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY1", has_video: false, video_url: "" },
      { date: "2026/8/9", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY2", has_video: false, video_url: "" },
      { date: "2026/8/16", venue: "幕張メッセ", name: "SUMMER SONIC 2026 TOKYO", has_video: true, video_url: "" }
    ]
  },
  {
    name: "The Whole Blue World",
    name_jp: "The Whole Blue World",
    album: "Best Album「Ave Música」",
    album_year: "2026",
    release_date: "2026/6/17",
    cover: "../images/精选通常.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "Diggy-MO' • 植木建象(SPAWN Inc.)",
    arranger: "Diggy-MO'",
    first_stage: "Coming Soon…",
    mv_url: "https://www.bilibili.com/video/BV18LjB6eEYm",
    lyrics_jp: "風よ 空よ 海よ 隙間に滑り込め\\n星よ 時代（とき）よ 真実（ひかり）よ 眼差しの奥で\\n燃えゆく命 駆け抜ける短さに\\n嘲う世界 闇を暴け\\nBlue, Blue, Blue World The Whole Blue World\\n砕け散ってゆく夢 ぼくら晒されて\\n震える夜を越え いま儚く消えた声\\n何故に 何故に こんなに届かない 苛立ち\\n足りない 足りない 言葉じゃ こんなんじゃ感じない\\nyour head up... stand up...\\n神のいないこの天（そら）\\nBlue,Blue,Blue World So Cruel World\\n立ち向かってゆく ぼくら約束の果て\\n美しい夜を越え さあ\\n確かなもの探していた 打ちひしがれて\\n運命を切り拓け\\n受け入れられないものを変えてゆけると\\n信じたいのに…信じたいのに…\\n信じていたのに\\nclose to you\\nただ終わりへと向かってゆくだけのその哀しみに\\n震える君を抱きしめ\\n追いかける\\nBlue,Blue,Blue World The Whole Blue World\\n砕け散ってゆく夢 ぼくらそのままで\\n震える夜を越え 嗚呼\\nいま",
    lyrics_cn: "风儿 天空 大海 滑入缝隙之中\\n星辰 时代 真相 在那眼神深处\\n持续燃烧的生命 如疾驰般短暂\\n在这嘲笑一切的世界上 暴露黑暗吧\\nBlue, Blue, Blue World The Whole Blue World\\n逐渐粉碎凋零的梦境 让我们无所遁形\\n穿越颤抖的黑夜 此刻 声音幻影般消失\\n为何 为何 如此地无法传达 这焦躁与不安\\n不够 不够 仅凭语言 无法让我感受到\\nyour head up... stand up...\\n神明不在的、这片天空\\nBlue, Blue, Blue World So Cruel World\\n我们挺身面对 向我们约定的尽头\\n穿越美丽的黑夜 来吧\\n即便心力交瘁 我仍在寻找确定之物\\n为了开拓命运\\n为了改变无法接受的事情\\n想要相信…想要相信…\\n曾经相信\\nclose to you\\n在那份只是逐渐走向终结的哀伤中\\n抱紧颤抖的你\\n追逐\\nBlue, Blue, Blue World The Whole Blue World\\n逐渐粉碎凋零的梦境 我们就这样\\n穿越颤抖的黑夜 啊啊\\n如今",
    appearances: ["Ave Música"],
    comments: [
      { text: "——刚才也提到过，作为新曲的「The Whole Blue World」是一首连接了 Ave Mujica 过去与未来的歌曲。 \\n佐佐木：是的呢。我觉得 Ave Mujica 给人一种孤高的印象。但是这首歌，感觉像是在歌颂共同坠落的美。看歌词的话，有很多像是“残酷的世界中”、“无法传达的焦躁”、“渐渐粉碎的梦境”、“感受到痛苦”之类的词汇。但在其中，依然有一种“想要切实地触碰你”的感觉。我觉得这部分的氛围和以前稍微有些不同。 歌词中出现了“我们”（僕ら）这个词，也让我印象非常深刻。应该说是一种选择一起受伤害的细腻感吗，其中也还有“明明想要去相信”的纠结和动摇的部分，我非常喜欢。带着这种动摇仍要继续前进的感觉，我觉得非常有 Ave Mujica 的风格。我是绷紧了神经，全神贯注地去演唱这首歌的。\\n冈田：我有个单纯的疑问，在录音的时候，你不会“哇——”地一下情绪失控吗？（笑）\\n 佐佐木：虽然不会“哇——”地叫出来（笑），但确实有一种自己正在坠入黑暗的感觉。在之前的采访中我也提到过，在唱「Sophie」的时候，回过神来发现手上全是伤痕，我应该是下意识地用力攥紧了手，在“真的好讨厌”“真的好讨厌”（ほんとヤダ）那里。就是这样，贴近着歌词的情感去演唱的。 这首歌也是，感觉像是让内心静静地沸腾起来。我会一边想象着那种包含着心中的焦躁、痛苦和软弱，却依然要继续前行的感觉，一边去演唱。\\n——「The Whole Blue World」里的“Blue World”，让人既能感受到清澈的蓝，也能感受到那种仿佛要深深沉沦下去的蓝。\\n佐佐木：确实，感觉它不仅仅是一个普通的蓝色世界。在其中既能感觉到充满透明感的蓝，也能感觉到深邃的蓝。非常有Ave Mujica的风格。我觉得Ave Mujica不仅仅是有攻击性，那种细腻而优雅的部分也是 Ave Mujica 的一部分。我认为这首歌是一首能够同时体会到这两面的歌曲。\\n\n冈田：真是一种不可思议的平衡呢。和声也录制了非常多的版本。Ave Mujica的歌曲，都是由 Diggy-MO' 先生来录制Demo的。听到Diggy-MO'先生的演唱，我们也能明确地明白“这首歌想要呈现出怎样的感觉”。而且，我能听出来李子亲并没有完全仿照，而是很好地将其升华为Doloris的风格来演唱。这点每次都让我很感动。其他的歌曲中，强调沉重感的曲子比较多，但这首歌相对来说，让我感受到了深沉感。\\n\n佐佐木：我确实是有意识地在表现这种深沉感！而且，也刻意去表现了那种带着冰冷感的蓝。并不是粗暴地去击打，而是那种优美地夺走你呼吸的感觉，你能体会到这一层我真的很高兴。 \\n冈田：太棒了！", source: "https://www.animatetimes.com/news/details.php?id=1781597468&p=2", from: "佐佐木李子&冈田梦以" }
    ],
    live_history: []
  },
  {
    name: "in your blue eyes",
    name_jp: "碧い瞳の中に",
    album: "Digital Single",
    album_year: "2025",
    release_date: "2025/9/4",
    cover: "../images/蓝眼睛.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "松坂康司 (SUPA LOVE)、Diggy-MO'",
    arranger: "松坂康司 (SUPA LOVE)、Diggy-MO'",
    first_stage: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演",
    mv_url: "https://www.bilibili.com/video/BV13Ma2zjEMA",
    lyrics_jp: "虜になっていた 光 うつらうつら\\n幻を見ていた 儚い夢の中\\nこの天（そら）の狭間に彷徨（さまよ）って 堕ちてゆく\\n[気づいて 気づいて このままじゃいけない]\\nそうね 知っているわ\\nwake up wake up babe don't fear\\n君の碧い瞳の中に ああ わたしはいたい\\nwake up wake up babe さあ いま\\nもういちど 自分を越えて 越えて\\n信じて\\n聖なる人も皆 生きる罪深さに苛まれ\\nやがて伝説は ただの土に\\nこの愛のあとにも また忘却が続くのかしら\\n[お願い お願い ねぇ 戻ってきて]\\nこのぬくもり 失えない\\nwake up wake up babe don't fear\\n君の碧い瞳が やさしく微笑む未来\\nwake up wake up babe さあ いま\\n奏でるの 世界を ともに描いて\\nwake up wake up babe don't fear\\n君の碧い瞳の中に ああ わたしはいたい\\nwake up wake up babe さあ いま\\nもういちど 自分を越えて 越えて\\n信じて",
    lyrics_cn: "曾深陷其中 光芒朦朦胧胧\\n曾见到模糊的幻想 在转瞬即逝的梦中\\n在天空的狭缝中彷徨徘徊 逐渐坠落\\n[请察觉到 请察觉到 不能这样下去了]\\n是啊 我早已明白\\n醒来吧 醒来吧 亲爱的 别害怕\\n我愿长存于你空灵美丽的眼眸之中\\n醒来吧 醒来吧 亲爱的 就是现在\\n再一次 去超越自我 超越吧\\n请相信吧\\n纵使是圣洁之人 也会为生命的罪孽深受煎熬\\n而那传说 终将化作尘土\\n这份爱之后 是否仍唯有忘却相随\\n[求求你 求求你 呐 回到我身边吧]\\n不能失去这份温暖\\n醒来吧 醒来吧 亲爱的 别害怕\\n你空灵美丽的眼眸中温柔微笑的未来\\n醒来吧 醒来吧 亲爱的 就是现在\\n奏响由我们共同描绘的世界\\n醒来吧 醒来吧 亲爱的 别害怕\\n我愿长存于你空灵美丽的眼眸之中\\n醒来吧 醒来吧 亲爱的 就是现在\\n再一次 去超越自我 超越吧\\n请相信吧",
    appearances: ["Ave Música"],
    comments: [
      { text: "明日方舟 Side Story 「无忧梦呓」 联动曲", source: "", from: "Tie-up" }
    ],
    live_history: [
      { date: "2025/12/14", venue: "東京国際フォーラム ホールA", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演", has_video: true, video_url: "https://www.acfun.cn/v/ac48116014" },
      { date: "2026/1/15", venue: "グランキューブ大阪 メインホール", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演", has_video: false, video_url: "" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac48116014_2" }
    ]
  },
  {
    name: "Black Birthday",
    name_jp: "黒のバースデイ",
    album: "Digital Single",
    album_year: "2023",
    release_date: "2023/4/10",
    cover: "../images/黑色生日.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "賀佐泰洋(SUPA LOVE)",
    arranger: "賀佐泰洋(SUPA LOVE)",
    first_stage: "Ave Mujica 0th LIVE 「Primo die in scaena」",
    mv_url: "https://www.bilibili.com/video/BV16v4y1H7ZR",
    lyrics_jp: "この領域まで侵されて そう プラットフォームは上下する\\n新しく記された my バースデイ 今夜 感じて 燃え 悶える\\nna, 生々しい艷やかな mad day 秘密めいた ruler loo-la, cool, cool,\\n“ようこそ おいでなさい” 告げる 始まりのとき\\nねぇ しなやかなつま先が ‘ゆらっ’描き出すわ輪舞曲(ロンド)\\n純白のドレスを さあ いま 染めて闇の色\\n殺める影よ 舞い上がれ\\n見える 見える 見えないものが ほら\\n生まれ変わる ああ 本当の私に\\nエンジェル・インターセプター concept 混乱のフェーズ 堕ちる術中\\nその小さな胸を引き裂いて\\nbloody lover, lover, la-la-la, bloody 散らばるよ 擦り切れたフィルム\\n場面 場面 蘇る 瞼の裏側で\\nねぇ 張り付く夜には また 究極の快楽が\\njack-jackie, 邪鬼 zap, zap, でもまだ 足りないよ足りない\\n求めて求めて 苛まれて\\n馳せる 馳せる 消えてゆく惑星(ほし)が ほら\\n宇宙(そら)のリスク 真実を歪めたなら\\ncallin' 呼び続けてもまだ darlin' 戻らない\\n誰もが 選ばれたパズルのピースに\\nこのまま このままでいい 世界をあげるわ\\n見える 見える 見えないものが ほら\\n生まれ変わる ああ 本当の私に\\noh, my..\\nblack-black, black, my black birthday",
    lyrics_cn: "连此领域也被侵蚀 是的 舞台升起降下\\n被重新记载的 my 诞生日 今晚 去感受 燃烧着 痛苦挣扎\\nna, 鲜活妖艳的 mad day 充斥秘密的 ruler loo-la, cool, cool, \\n“欢迎前来 请过来这里” 宣告着 起始之时刻\\n呐啊 柔软优美的足尖 摇荡勾勒轮舞曲\\n将那纯白的礼服 来吧 此刻 染上黑暗之色\\n杀戮的暗影啊 升腾而起吧 \\n看见了 看见了 本不可见之物 看啊\\n重获新生 啊啊 成为真正的我\\n天使拦截者 concept 混乱的局面 堕入陷阱之中\\n将那小小的胸膛撕裂\\nbloody lover, lover, la-la-la, bloody 散落一地啊 磨损的胶片\\n一幕幕场景 重新浮现 在眼帘之后\\n呐啊 在这黏着不去的夜里 再一次 极致的快感…\\njack-jackie, 邪鬼 zap, zap, 但还不够啊 还远远不够啊\\n追求着渴望着 被折磨着\\n奔驰着 奔驰着 逐渐消逝的行星 看啊\\n若要扭曲真实 则将承受宇宙的风险\\ncallin' 即使不断呼喊 darlin' 也不会回来\\n无论是谁 都会被选中成为拼图的碎片\\n这样就好 维持这样就好 我会给你整个世界\\n看见了 看见了 本不可见之物 看啊\\n重获新生 啊啊 成为真正的我\\noh, my..\\nblack-black, black, my black birthday",
    appearances: ["Alea jacta est", "Ave Música"],
    comments: [
      { text: "Debut track", source: "", from: "Remark" },
      { text: "——感觉还能通宵畅聊呢（笑）。那么，如果要选一首特别有感情的乐曲的话？\\n\n高尾：真的很难选……我可能会选「黒のバースデイ」。因为它是0th LIVE上第一首演奏的歌曲，演奏的时候会有一种瞬间回到那个时候的感觉。或者说，能让我找回初心。\\n\n米泽：我懂！有一种穿着黑袍的感觉。\\n\n渡濑：确实（笑）。对观众来说，如果要说Ave Mujica的代表曲可能会想到「Ave Mujica」，但对我们来说，「黒のバースデイ」才是真正开始的曲子。最早练习的也是这首歌。\\n\n佐佐木：而且，它也是一首仿佛在为 Mujica 的诞生送上祝福的歌曲。\\n", source: "https://www.lisani.jp/0000271996/2/?show_more=1", from: "全员" }
    ],
    live_history: [
      { date: "2023/6/4", venue: "中野サンプラザホール", name: "Ave Mujica 0th LIVE 「Primo die in scaena」", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539" },
      { date: "2024/1/27", venue: "横須賀芸術劇場", name: "Ave Mujica 1st LIVE 「Perdere Omnia」", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_2" },
      { date: "2024/3/9", venue: "神戸ワールド記念ホール", name: "MEGA VEGAS 2024", has_video: false, video_url: "" },
      { date: "2024/6/8", venue: "神奈川県民ホール 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」神奈川公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_3" },
      { date: "2024/7/7", venue: "愛知県芸術劇場 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」爱知公演", has_video: false, video_url: "" },
      { date: "2024/7/13", venue: "SHANGHAI NECC HONG ARENA", name: "BILIBILI MACRO LINK 2024 DAY1", has_video: false, video_url: "" },
      { date: "2024/7/14", venue: "SHANGHAI NECC HONG ARENA", name: "BILIBILI MACRO LINK 2024 DAY2", has_video: false, video_url: "" },
      { date: "2024/10/13", venue: "河口湖ステラシアター", name: "Ave Mujica 3rd LIVE「Veritas」", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_4" },
      { date: "2024/12/15", venue: "武蔵野の森総合スポーツプラザ", name: "Ave Mujica 4th LIVE「Adventus」", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_5" },
      { date: "2025/1/25", venue: "日本武道館", name: "リスアニ!LIVE 2025 SATURDAY STAGE", has_video: false, video_url: "" },
      { date: "2025/2/2", venue: "KT Zepp Yokohama", name: "Ave Mujica「KiLLKiSS」購入者限定フリーライブ", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_6" },
      { date: "2025/7/26", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_7" },
      { date: "2025/7/27", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_8" },
      { date: "2025/12/14", venue: "東京国際フォーラム ホールA", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_9" },
      { date: "2026/1/15", venue: "グランキューブ大阪 メインホール", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演", has_video: false, video_url: "" },
      { date: "2026/3/1", venue: "Kアリーナ横浜", name: "MyGO!!!!!×Ave Mujica ツーマンライブ「“moment / memory”」", has_video: true, video_url: "https://www.acfun.cn/v/ac47932539_10" },
      { date: "2026/4/11", venue: "台北・大佳河濱公園", name: "BanG Dream! Special LIVE in TAIPEI DAY1 : MyGO!!!!!×Ave Mujica「\"moment / memory\"」", has_video: false, video_url: "" },
      { date: "2026/4/17", venue: "Zepp Fukuoka", name: "Ave Mujica LIVE TOUR 2026「Exitus」福冈公演", has_video: false, video_url: "" },
      { date: "2026/4/26", venue: "Zepp Namba", name: "Ave Mujica LIVE TOUR 2026「Exitus」大阪公演", has_video: false, video_url: "" },
      { date: "2026/5/1", venue: "Zepp Nagoya", name: "Ave Mujica LIVE TOUR 2026「Exitus」爱知公演", has_video: false, video_url: "" },
      { date: "2026/5/4", venue: "Zepp Haneda (TOKYO)", name: "Ave Mujica LIVE TOUR 2026「Exitus」东京公演", has_video: false, video_url: "" },
      { date: "2026/6/19", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac48752036" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac48752036_2" },
      { date: "2026/8/8", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY1", has_video: false, video_url: "" },
      { date: "2026/8/9", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY2", has_video: false, video_url: "" }
    ]
  },
  {
    name: "Two Moons",
    name_jp: "ふたつの月 ~Deep Into The Forest~",
    album: "Digital Single",
    album_year: "2023",
    release_date: "2023/4/16",
    cover: "../images/双月.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "長谷川大介(SUPA LOVE)",
    arranger: "長谷川大介(SUPA LOVE)",
    first_stage: "Ave Mujica 0th LIVE 「Primo die in scaena」",
    mv_url: "https://www.bilibili.com/video/BV1vs4y127DJ",
    lyrics_jp: "ああ 深く 深く 迷い込んだ森で\\nなぜか私を開いて壊すもの そう そして 感じさせるもの\\n木から落ちる leaf に ほらいま 映り込む未来\\nこの風 吹き抜けるとき 私は祈り人(prayer)\\nおしえてよ おしえてよ こんなに美しいのはなぜ\\n惹かれてく 堕ちてく 月が笑う夜\\n銀のトレーにフルーツを キャンドルホルダーに火を\\nこのまま いくつかの意味をさがすの その幻を暴きたい\\n常に終わりは始まりと組まれる 不思議な creation\\nこの風 命集めて いま 昇るなら\\nおしえてよ おしえてよ こんなに苦しいのはなぜ\\n鏡の中の彼女が 嘲笑う夜\\n大気の重さで もうひとつの月が顔を出す\\n“早く目覚めて ここで眠ってしまわないように”\\nおしえてよ おしえてよ こんなに美しいのはなぜ\\n惹かれてく 堕ちてく 月が笑う夜",
    lyrics_cn: "啊啊 深深地 深深地 迷失在森林中\\n某物莫名将我剖开破坏 是啊 而后又让我有所感受\\n从树上落下的 leaf 上 看吧 此刻 正映照着未来\\n当这阵风吹过时 我即是祈祷者（prayer）\\n请告诉我 请告诉我吧 为何如此美丽动人\\n渐受蛊惑 步步坠落 月亮嗤笑之夜\\n将果实盛入银盘 为烛台点燃火焰\\n就这样 寻找种种意义 渴望揭穿那重幻象\\n结束总与开始交织纠缠 不可思议的 creation\\n这阵风 汇聚生命 现在 若能升腾而起\\n请告诉我 请告诉我吧 为何如此痛苦难耐\\n镜中的她 嘲弄之夜\\n大气的重压之下 另一轮月亮显露真容\\n“快快醒来 可不要在此处沉睡”\\n请告诉我 请告诉我吧 为何如此美丽动人\\n渐受蛊惑 步步坠落 月亮嗤笑之夜",
    appearances: ["Alea jacta est"],
    comments: [
      { text: "——初华和祥子，换句话说也就是 Doloris 和 Oblivionis，在演唱会上也有很多像「双月 ~Deep Into The Forest~」和「Symbol III : ▽」这样成对出现的演出呢。\\n高尾：大家也都非常敏锐地感受到了呢。我每次在演唱会上都会想着“请期待动画！”（笑）\\n渡濑：初华从动画的先导预告片时期开始，被截取出来的台词就几乎全都和祥子有关呢。我想大家从那个阶段开始，应该就已经察觉到一些端倪了吧（笑）。", source: "https://www.lisani.jp/0000274367/4/?show_more=1", from: "渡濑结月&高尾奏音" }
    ],
    live_history: [
      { date: "2023/6/4", venue: "中野サンプラザホール", name: "Ave Mujica 0th LIVE 「Primo die in scaena」", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075" },
      { date: "2024/1/27", venue: "横須賀芸術劇場", name: "Ave Mujica 1st LIVE 「Perdere Omnia」", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075_2" },
      { date: "2024/3/9", venue: "神戸ワールド記念ホール", name: "MEGA VEGAS 2024", has_video: false, video_url: "" },
      { date: "2024/6/8", venue: "神奈川県民ホール 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」神奈川公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075_3" },
      { date: "2024/7/7", venue: "愛知県芸術劇場 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」爱知公演", has_video: false, video_url: "" },
      { date: "2024/10/13", venue: "河口湖ステラシアター", name: "Ave Mujica 3rd LIVE「Veritas」", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075_4" },
      { date: "2024/12/15", venue: "武蔵野の森総合スポーツプラザ", name: "Ave Mujica 4th LIVE「Adventus」", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075_5" },
      { date: "2025/12/14", venue: "東京国際フォーラム ホールA", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47931075_6" },
      { date: "2026/1/15", venue: "グランキューブ大阪 メインホール", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演", has_video: false, video_url: "" }
    ]
  },
  {
    name: "Choir 'S' Choir",
    name_jp: "Choir 'S' Choir",
    album: "Digital Single",
    album_year: "2023",
    release_date: "2023/4/23",
    cover: "../images/CSC.webp",
    type: "原创",
    lyricist: "Diggy-MO'",
    composer: "角本麻衣(SUPA LOVE)",
    arranger: "角本麻衣(SUPA LOVE)",
    first_stage: "Ave Mujica 0th LIVE 「Primo die in scaena」",
    mv_url: "https://www.bilibili.com/video/BV1Xg4y1j7Lt",
    lyrics_jp: "[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa]\\nChoir Choir, Choir Choir ‘S’ Choir\\nそう サジェスチョンなら Spade 彷徨うスペクター [Spiritual, So Spiritual]\\nイミテーションやら聖なる讃美歌 [Sensual, So Sensual]\\nサディスティック サディスティック 堕天使\\nヒステリック ヒステリック 宿る刻\\n[look, 歌う胸像 the show must go on ルカ 精霊 精霊 ghost, oh, it's comin']\\n‘信じる？ 信じない？’ いないいないばあ\\n感情の万華鏡 引きずり込むのは\\nねぇ誰？ ねぇ誰？ 叫ぶ声が\\n夜に酔えば 真っ赤に腫れた唇がわたしを貪るの\\n‘S’ カレート ‘S’ カレート 忍び寄るわ mysterious\\n目眩く描くほどに 狂い咲くカーニヴァル\\nChoir Choir, Choir Choir ‘S’ Choir\\noh, イリュージョンなら左手のジェスチャー [Spiritual, So Spiritual]\\nテンプテーション 神話にはつづきが [Sensual, So Sensual]\\nサタニック サタニック マジェスティ\\nヒプノティック ヒプノティック 裁く刻\\n[see, 'il giudizio, la giustizia' 下る極彩色 shockin' psychic]\\n‘感じる？ 感じない？’ お気に召す mo'\\n触れてみて 触れてみて 試されてもいい\\nねぇ誰？ ねぇ誰？ 甘い夢が\\n闇に占う カードの悪魔 誘う魂の行方 今\\n‘S’ カレート ‘S’ カレート 気の触れた my desire\\n鼓膜を劈くほどに 咽び泣くアリア\\n[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa,\\ndaa-mennus, daa-menn, philis-poliaa, daa-la-la-daa-daa]\\nああ ワルツに身を委ねて ゆらゆらゆら\\n誰？ ねぇ誰？ 叫ぶ声が\\n夜に酔えば 真っ赤に腫れた唇がわたしを貪るの\\n‘S’ カレート ‘S’ カレート 忍び寄るわ mysterious\\n目眩く描くほどに 狂い咲くカーニヴァル\\n[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa,\\ndaa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa]\\nChoir Choir, Choir Choir ‘S’ Choir",
    lyrics_cn: "[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa]\\nChoir Choir, Choir Choir ‘S’ Choir\\n是的 若要给出暗示 Spade 彷徨的幽灵 [Spiritual, So Spiritual]\\n赝品亦或是神圣的赞美歌 [Sensual, So Sensual]\\n嗜虐的 嗜虐的 堕天使\\n癔病的 癔病的 附身之时\\n[look, 歌唱的胸像 the show must go on 路加 精灵 精灵 ghost, oh, it's comin']\\n‘相信？ 不相信’ 不在、不在、在这里\\n感情的万华镜 被卷入其中的是\\n是谁？ 是谁？ 是谁正在呼喊\\n沉醉于夜晚 鲜红肿胀的嘴唇将我贪婪吞噬\\n‘S’calate ‘S’calate 悄然接近的 mysterious\\n勾勒到目眩神迷 癫狂盛放的狂欢\\nChoir Choir, Choir Choir ‘S’ Choir\\noh, 若是幻觉则用左手的手势 [Spiritual, So Spiritual]\\n诱惑 神话仍未终结 [Sensual, So Sensual]\\n恶魔般的 恶魔般的 无上威严\\n催眠的 催眠的 裁决之时\\n[see, 'il giudizio, la giustizia' 降临的绚丽色彩 shockin' psychic]\\n‘感觉到？ 感觉不到？’如你所愿 mo'\\n试着触摸 试着触摸 即使受到考验也无妨\\n是谁？ 是谁？ 将这甜美的梦…\\n向黑暗问卜 卡牌的恶魔 引诱灵魂的去向 此刻\\n‘S’calate ‘S’calate 陷入疯狂的 my desire\\n似要刺破鼓膜一般 呜咽的咏叹调\\n[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa,\\ndaa-mennus, daa-menn, philis-poliaa, daa-la-la-daa-daa]\\n啊啊 委身于华尔兹吧 摇摇晃晃\\n是谁？ 是谁？ 是谁正在呼喊\\n沉醉于夜晚 鲜红肿胀的嘴唇将我贪婪吞噬\\n‘S’calate ‘S’calate 悄然接近的 mysterious\\n勾勒到目眩神迷 癫狂盛放的狂欢\\n[daa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa,\\ndaa-mennus, daa-menn, philis-poliaa, taa-mennus, taa-menn, jealis-moliaa]\\nChoir Choir, Choir Choir ‘S’ Choir",
    appearances: ["Alea jacta est", "Ave Música"],
    comments: [
      { text: "我觉得比较棘手的一首歌是「Choir ‘S’ Choir」。在大家都在踩正拍节奏的时候，唯独贝斯走的是反拍。此外，由于曲速很快、乐句也很细密，实际上在曲子中，我需要不断切换使用下拨和交替拨弦。虽然像这样极具挑战性的曲子有很多，但弹奏「Ave Mujica」总之就是非常开心（笑）。尤其喜欢变成三拍子那一段的乐句。", source: "https://www.oricon.co.jp/news/2294611/full/", from: "冈田梦以" },
      { text: "——接下来请谈谈迷你专辑「Alea jacta est」。这张专辑收录了以重型乐器编排打造的硬核金属音效为主轴的共6首歌曲，能请各位说说各自最推的歌曲吗？\\n\n渡濑：刚才我们也稍微聊到了推的歌曲，当时めいしゃん（冈田）提到的「Choir ‘S’ Choir」我也很喜欢。虽然还不能详细透露，其实Ave Mujica的每首歌都有各自的主题元素（Theme），在看到0th LIVE的演出时，我发现这首歌正是沿着那个主题展开的，就觉得“就是这个！”而感觉很感动。从那以后一下子就喜欢上了。\\n\n佐佐木：我录音的时候也被告知了每首歌的母题（Motif），是注意着那种意象和世界观去演唱的。歌词里，Diggy-MO’先生独特的措辞和故事之中，也散落着与那个主题相关的关键词，希望大家一定要去考察解读。\\n\n渡濑：めいしゃん为什么最推「Choir ‘S’ Choir」？\\n\n冈田：因为这首的贝斯在原创曲里是最难的，跟它较劲的时间也比较长，还有就是我在这首歌里很喜欢李子酱的演唱。我觉得她对声音的运用以及演唱技巧的储备极其丰富，比如还加入了一点嘶吼式的唱法。\\n\n佐佐木：诶——好开心！不过「Choir ‘S’ Choir」里大家的和声也很多，所以完成得非常华丽呢。\\n\n冈田：のんたん（高尾）的念白也很棒。\\n\n高尾：谢谢！其他还有「Mas?uerade Rhapsody Re?uest」里也有念白，祥子在歌曲里就会突然开始说英语（笑）。而且「Choir ‘S’ Choir」里的rap部分还是拉丁语。还有，这个可能谁都没有注意到，在「神さま、バカ」副歌结尾的“神さま、バカ”那里，用耳语声加入了一句“神さま、バカ”的念白，其实那也是我（笑）。\\n\n（中略）\\n\n米泽：我也推「Choir ‘S’ Choir」当作推的歌曲。除此之外，「Ave Mujica」是我们最早拿到的歌曲，单纯是听得最多的一首，而且乐队名直接就是歌名，所以觉得这是很能代表我们的歌，感情很深。", source: "https://www.animatetimes.com/news/details.php?id=1711341820&p=3", from: "全员" },
      { text: "高尾：（笑）。比如说，「Choir ‘S’ Choir」的话，就是想象着在草原上弹奏的感觉。我会在自己心里变换场景意象来演奏，所以刚才被你说中，吓了一跳。\\n\n佐佐木：我一直都感觉得到哦！\\n\n高尾：好厉害！我们心意相通了啊！\\n", source: "https://www.animatetimes.com/news/details.php?id=1711341820&p=3", from: "佐佐木李子&高尾奏音" }
    ],
    live_history: [
      { date: "2023/6/4", venue: "中野サンプラザホール", name: "Ave Mujica 0th LIVE 「Primo die in scaena」", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101" },
      { date: "2024/1/27", venue: "横須賀芸術劇場", name: "Ave Mujica 1st LIVE 「Perdere Omnia」", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_2" },
      { date: "2024/3/9", venue: "神戸ワールド記念ホール", name: "MEGA VEGAS 2024", has_video: false, video_url: "" },
      { date: "2024/6/8", venue: "神奈川県民ホール 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」神奈川公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_3" },
      { date: "2024/7/7", venue: "愛知県芸術劇場 大ホール", name: "Ave Mujica 2nd LIVE「Quaerere Lumina」爱知公演", has_video: false, video_url: "" },
      { date: "2024/10/13", venue: "河口湖ステラシアター", name: "Ave Mujica 3rd LIVE「Veritas」", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_4" },
      { date: "2024/12/15", venue: "武蔵野の森総合スポーツプラザ", name: "Ave Mujica 4th LIVE「Adventus」", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_5" },
      { date: "2025/2/2", venue: "KT Zepp Yokohama", name: "Ave Mujica「KiLLKiSS」購入者限定フリーライブ", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_6" },
      { date: "2025/7/26", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_7" },
      { date: "2025/7/27", venue: "LaLa arena TOKYO-BAY", name: "Ave Mujica 5th LIVE「Nova Historia」DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_8" },
      { date: "2025/12/14", venue: "東京国際フォーラム ホールA", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 东京公演", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_9" },
      { date: "2026/1/15", venue: "グランキューブ大阪 メインホール", name: "Ave Mujica 6th LIVE 「Ulterius Procedere」 大阪公演", has_video: false, video_url: "" },
      { date: "2026/3/1", venue: "Kアリーナ横浜", name: "MyGO!!!!!×Ave Mujica ツーマンライブ「“moment / memory”」", has_video: true, video_url: "https://www.acfun.cn/v/ac47935101_10" },
      { date: "2026/4/11", venue: "台北・大佳河濱公園", name: "BanG Dream! Special LIVE in TAIPEI DAY1 : MyGO!!!!!×Ave Mujica「\"moment / memory\"」", has_video: false, video_url: "" },
      { date: "2026/4/17", venue: "Zepp Fukuoka", name: "Ave Mujica LIVE TOUR 2026「Exitus」福冈公演", has_video: false, video_url: "" },
      { date: "2026/4/26", venue: "Zepp Namba", name: "Ave Mujica LIVE TOUR 2026「Exitus」大阪公演", has_video: false, video_url: "" },
      { date: "2026/5/1", venue: "Zepp Nagoya", name: "Ave Mujica LIVE TOUR 2026「Exitus」爱知公演", has_video: false, video_url: "" },
      { date: "2026/5/4", venue: "Zepp Haneda (TOKYO)", name: "Ave Mujica LIVE TOUR 2026「Exitus」东京公演", has_video: false, video_url: "" },
      { date: "2026/6/19", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY1", has_video: true, video_url: "https://www.acfun.cn/v/ac48752881" },
      { date: "2026/6/20", venue: "SGC HALL ARIAKE", name: "Ave Mujica LIVE TOUR 2026「Exitus」-FINAL- DAY2", has_video: true, video_url: "https://www.acfun.cn/v/ac48752881_2" },
      { date: "2026/8/8", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY1", has_video: false, video_url: "" },
      { date: "2026/8/9", venue: "國立體育大學綜合體育館（林口體育館）", name: "Ave Mujica LIVE TOUR 2026「Exitus」台北追加公演 DAY2", has_video: false, video_url: "" }
    ]
  }
];
